import Heights.ModularJ

set_option linter.style.header false

/-!
# Arithmetic and archimedean realization certificates

Mathlib does not currently assemble local minimal models over a number field
into a global minimal-discriminant ideal, nor does it uniformize an algebraic
elliptic curve over `ℂ` and identify its algebraic `j` with `Heights.modularJ`.
This file gives explicit interfaces for exactly that missing realization data.
None of these structures contains a height, a height formula, a comparison
bound, or an existence claim.
-/

open scoped NumberField UpperHalfPlane nonZeroDivisors
open NumberField IsDedekindDomain

namespace Heights

/-- Coefficient integrality of a Weierstrass equation at one number-field
prime, stated using mathlib's multiplicative prime valuation. -/
structure IsIntegralAt
    (K : Type*) [Field K] [NumberField K]
    (v : HeightOneSpectrum (𝓞 K)) (W : WeierstrassCurve K) : Prop where
  /-- Integrality of `a₁` at `v`. -/
  a₁ : v.valuation K W.a₁ ≤ 1
  /-- Integrality of `a₂` at `v`. -/
  a₂ : v.valuation K W.a₂ ≤ 1
  /-- Integrality of `a₃` at `v`. -/
  a₃ : v.valuation K W.a₃ ≤ 1
  /-- Integrality of `a₄` at `v`. -/
  a₄ : v.valuation K W.a₄ ≤ 1
  /-- Integrality of `a₆` at `v`. -/
  a₆ : v.valuation K W.a₆ ≤ 1

/-- A variable change realizing the minimal discriminant exponent at one
number-field prime. In multiplicative valuation conventions, additive order
`n` is represented by `exp (-n)`, and minimality is maximality of the
multiplicative valuation among integral changes. -/
structure IsLocalMinimalDiscriminantExponent
    (K : Type*) [Field K] [NumberField K]
    (v : HeightOneSpectrum (𝓞 K))
    (W : WeierstrassCurve K) (n : ℕ) where
  /-- A change of variables realizing the local minimum. -/
  change : WeierstrassCurve.VariableChange K
  /-- The changed equation is integral at the prime. -/
  integral : IsIntegralAt K v (change • W)
  /-- Its discriminant has additive order `n`. -/
  exponent : v.valuation K (change • W).Δ = WithZero.exp (-(n : ℤ))
  /-- No integral change has larger multiplicative discriminant valuation. -/
  maximal : ∀ C : WeierstrassCurve.VariableChange K,
    IsIntegralAt K v (C • W) →
      v.valuation K (C • W).Δ ≤ WithZero.exp (-(n : ℤ))

/-- A nonzero integral ideal whose prime multiplicities realize all local
minimal discriminant exponents. This packages global assembly data but does
not assert that such data exists for every curve. -/
structure GlobalMinimalDiscriminantData
    (K : Type*) [Field K] [NumberField K]
    (W : WeierstrassCurve K) [W.IsElliptic] where
  /-- The assembled minimal-discriminant ideal. -/
  ideal : Ideal (𝓞 K)
  /-- The assembled ideal is nonzero. -/
  ideal_ne_bot : ideal ≠ ⊥
  /-- Every prime multiplicity realizes the corresponding local minimum. -/
  realizes : ∀ v : HeightOneSpectrum (𝓞 K),
    IsLocalMinimalDiscriminantExponent K v W
      (multiplicity v.asIdeal ideal)

/-- Fundamental-domain period ratios compatible with the embedded algebraic
`j`-invariant. This is the precise complex-uniformization bridge currently
missing from mathlib; no analytic estimate is included as a field. -/
structure ArchimedeanPeriodData
    (K : Type*) [Field K] [NumberField K]
    (W : WeierstrassCurve K) [W.IsElliptic] where
  /-- A period ratio at each infinite place. -/
  τ : InfinitePlace K → ℍ
  /-- Every chosen ratio lies in the standard fundamental domain. -/
  mem_fd : ∀ v, τ v ∈ ModularGroup.fd
  /-- Modular `j` agrees with the embedded algebraic invariant. -/
  j_eq : ∀ v, v.embedding W.j = modularJ (τ v)

/-- Coprime integral numerator and denominator ideals for the principal
fractional ideal generated by `x`, including the required normalization at
`x = 0`. This temporary interface contains no height identity. -/
structure ReducedPrincipalIdealData
    (K : Type*) [Field K] [NumberField K] (x : K) where
  /-- The integral numerator ideal. -/
  numerator : Ideal (𝓞 K)
  /-- The integral denominator ideal. -/
  denominator : Ideal (𝓞 K)
  /-- The denominator is nonzero. -/
  denominator_ne_bot : denominator ≠ (⊥ : Ideal (𝓞 K))
  /-- The numerator is nonzero when `x` is. -/
  numerator_ne_bot : (x ≠ 0) → numerator ≠ (⊥ : Ideal (𝓞 K))
  /-- At zero, use numerator `⊥` and denominator `⊤`. -/
  zero_normalization : (x = 0) →
    numerator = (⊥ : Ideal (𝓞 K)) ∧ denominator = (⊤ : Ideal (𝓞 K))
  /-- Numerator and denominator have no common prime factor. -/
  coprime : IsCoprime numerator denominator
  /-- The quotient of ideals represents the principal fractional ideal. -/
  span_eq : FractionalIdeal.spanSingleton (𝓞 K)⁰ x =
    FractionalIdeal.coeIdeal numerator /
      FractionalIdeal.coeIdeal denominator

end Heights
