import Heights.ModularJ

set_option linter.style.header false

/-!
# Arithmetic and archimedean realization certificates

Mathlib does not currently assemble local minimal models over a number field
into a global minimal-discriminant ideal, nor does it uniformize an algebraic
elliptic curve over `ℂ` and identify its algebraic `j` with `Heights.modularJ`.
This file gives explicit interfaces for exactly that missing realization data.
None of these structures contains a height, a height formula, a comparison
bound, or an existence claim.
-/

open scoped NumberField UpperHalfPlane nonZeroDivisors
open NumberField IsDedekindDomain

namespace Heights

/-- Coefficient integrality of a Weierstrass equation at one number-field
prime, stated using mathlib's multiplicative prime valuation. -/
structure IsIntegralAt
    (K : Type*) [Field K] [NumberField K]
    (v : HeightOneSpectrum (𝓞 K)) (W : WeierstrassCurve K) : Prop where
  /-- Integrality of `a₁` at `v`. -/
  a₁ : v.valuation K W.a₁ ≤ 1
  /-- Integrality of `a₂` at `v`. -/
  a₂ : v.valuation K W.a₂ ≤ 1
  /-- Integrality of `a₃` at `v`. -/
  a₃ : v.valuation K W.a₃ ≤ 1
  /-- Integrality of `a₄` at `v`. -/
  a₄ : v.valuation K W.a₄ ≤ 1
  /-- Integrality of `a₆` at `v`. -/
  a₆ : v.valuation K W.a₆ ≤ 1

/-- A variable change realizing the minimal discriminant exponent at one
number-field prime. In multiplicative valuation conventions, additive order
`n` is represented by `exp (-n)`, and minimality is maximality of the
multiplicative valuation among integral changes. -/
structure IsLocalMinimalDiscriminantExponent
    (K : Type*) [Field K] [NumberField K]
    (v : HeightOneSpectrum (𝓞 K))
    (W : WeierstrassCurve K) (n : ℕ) where
  /-- A change of variables realizing the local minimum. -/
  change : WeierstrassCurve.VariableChange K
  /-- The changed equation is integral at the prime. -/
  integral : IsIntegralAt K v (change • W)
  /-- Its discriminant has additive order `n`. -/
  exponent : v.valuation K (change • W).Δ = WithZero.exp (-(n : ℤ))
  /-- No integral change has larger multiplicative discriminant valuation. -/
  maximal : ∀ C : WeierstrassCurve.VariableChange K,
    IsIntegralAt K v (C • W) →
      v.valuation K (C • W).Δ ≤ WithZero.exp (-(n : ℤ))

/-- A nonzero integral ideal whose prime multiplicities realize all local
minimal discriminant exponents. This packages global assembly data but does
not assert that such data exists for every curve. -/
structure GlobalMinimalDiscriminantData
    (K : Type*) [Field K] [NumberField K]
    (W : WeierstrassCurve K) [W.IsElliptic] where
  /-- The assembled minimal-discriminant ideal. -/
  ideal : Ideal (𝓞 K)
  /-- The assembled ideal is nonzero. -/
  ideal_ne_bot : ideal ≠ ⊥
  /-- Every prime multiplicity realizes the corresponding local minimum. -/
  realizes : ∀ v : HeightOneSpectrum (𝓞 K),
    IsLocalMinimalDiscriminantExponent K v W
      (multiplicity v.asIdeal ideal)

/-- Fundamental-domain period ratios compatible with the embedded algebraic
`j`-invariant. This is the precise complex-uniformization bridge currently
missing from mathlib; no analytic estimate is included as a field. -/
structure ArchimedeanPeriodData
    (K : Type*) [Field K] [NumberField K]
    (W : WeierstrassCurve K) [W.IsElliptic] where
  /-- A period ratio at each infinite place. -/
  τ : InfinitePlace K → ℍ
  /-- Every chosen ratio lies in the standard fundamental domain. -/
  mem_fd : ∀ v, τ v ∈ ModularGroup.fd
  /-- Modular `j` agrees with the embedded algebraic invariant. -/
  j_eq : ∀ v, v.embedding W.j = modularJ (τ v)

/-- Coprime integral numerator and denominator ideals for the principal
fractional ideal generated by `x`, including the required normalization at
`x = 0`. This temporary interface contains no height identity. -/
structure ReducedPrincipalIdealData
    (K : Type*) [Field K] [NumberField K] (x : K) where
  /-- The integral numerator ideal. -/
  numerator : Ideal (𝓞 K)
  /-- The integral denominator ideal. -/
  denominator : Ideal (𝓞 K)
  /-- The denominator is nonzero. -/
  denominator_ne_bot : denominator ≠ (⊥ : Ideal (𝓞 K))
  /-- The numerator is nonzero when `x` is. -/
  numerator_ne_bot : (x ≠ 0) → numerator ≠ (⊥ : Ideal (𝓞 K))
  /-- At zero, use numerator `⊥` and denominator `⊤`. -/
  zero_normalization : (x = 0) →
    numerator = (⊥ : Ideal (𝓞 K)) ∧ denominator = (⊤ : Ideal (𝓞 K))
  /-- Numerator and denominator have no common prime factor. -/
  coprime : IsCoprime numerator denominator
  /-- The quotient of ideals represents the principal fractional ideal. -/
  span_eq : FractionalIdeal.spanSingleton (𝓞 K)⁰ x =
    FractionalIdeal.coeIdeal numerator /
      FractionalIdeal.coeIdeal denominator

/-- Every number-field element admits a reduced principal-ideal representation.

For a nonzero `x`, first write `x = n / d`. The sum of the principal ideals
`(n)` and `(d)` is their ideal-theoretic gcd. Cancelling it from both ideals
produces a coprime numerator and denominator. At zero we use the normalization
specified by `ReducedPrincipalIdealData`: numerator `⊥` and denominator `⊤`. -/
theorem exists_reducedPrincipalIdealData
    (K : Type*) [Field K] [NumberField K] (x : K) :
    Nonempty (ReducedPrincipalIdealData K x) := by
  by_cases hx : x = 0
  · subst x
    exact ⟨
      { numerator := ⊥
        denominator := ⊤
        denominator_ne_bot := top_ne_bot
        numerator_ne_bot := fun h => (h rfl).elim
        zero_normalization := fun _ => ⟨rfl, rfl⟩
        coprime := (Ideal.isCoprime_iff_sup_eq).mpr (by simp)
        span_eq := by simp }⟩
  · obtain ⟨n, d, hnd⟩ := IsLocalization.exists_mk'_eq (𝓞 K)⁰ x
    have hn : n ≠ 0 := by
      intro hn
      apply hx
      rw [← hnd, hn, IsFractionRing.mk'_eq_div, map_zero, zero_div]
    have hd : (d : 𝓞 K) ≠ 0 := nonZeroDivisors.coe_ne_zero d
    let N : Ideal (𝓞 K) := Ideal.span {n}
    let Q : Ideal (𝓞 K) := Ideal.span {(d : 𝓞 K)}
    let G : Ideal (𝓞 K) := N ⊔ Q
    have hN : N ≠ ⊥ := mt Ideal.span_singleton_eq_bot.mp hn
    have hQ : Q ≠ ⊥ := mt Ideal.span_singleton_eq_bot.mp hd
    have hG : G ≠ ⊥ := by
      intro h
      apply hN
      exact le_bot_iff.mp (h ▸ le_sup_left)
    have hGN : G ∣ N := Ideal.dvd_iff_le.mpr le_sup_left
    have hGQ : G ∣ Q := Ideal.dvd_iff_le.mpr le_sup_right
    let A : Ideal (𝓞 K) := Classical.choose hGN
    let D : Ideal (𝓞 K) := Classical.choose hGQ
    have hNA : N = G * A := Classical.choose_spec hGN
    have hQD : Q = G * D := Classical.choose_spec hGQ
    have hA : A ≠ ⊥ := by
      intro h
      apply hN
      rw [hNA, h, Ideal.mul_bot]
    have hD : D ≠ ⊥ := by
      intro h
      apply hQ
      rw [hQD, h, Ideal.mul_bot]
    refine ⟨
      { numerator := A
        denominator := D
        denominator_ne_bot := hD
        numerator_ne_bot := fun _ => hA
        zero_normalization := fun h => (hx h).elim
        coprime := (Ideal.isCoprime_iff_sup_eq).mpr ?_
        span_eq := ?_ }⟩
    · apply mul_left_cancel₀ hG
      rw [Ideal.mul_sup, ← hNA, ← hQD]
      simp [G]
    · rw [← hnd, IsFractionRing.mk'_eq_div,
        ← FractionalIdeal.spanSingleton_div_spanSingleton,
        ← FractionalIdeal.coeIdeal_span_singleton,
        ← FractionalIdeal.coeIdeal_span_singleton]
      change (N : FractionalIdeal (𝓞 K)⁰ K) / (Q : FractionalIdeal (𝓞 K)⁰ K) =
        (A : FractionalIdeal (𝓞 K)⁰ K) / (D : FractionalIdeal (𝓞 K)⁰ K)
      rw [hNA, hQD,
        FractionalIdeal.coeIdeal_mul, FractionalIdeal.coeIdeal_mul]
      exact mul_div_mul_left _ _ (FractionalIdeal.coeIdeal_ne_zero.mpr hG)

/-- A chosen reduced principal-ideal representation of any number-field
element. This removes the need to assume `ReducedPrincipalIdealData` as
external certificate data. -/
noncomputable def reducedPrincipalIdealData
    (K : Type*) [Field K] [NumberField K] (x : K) :
    ReducedPrincipalIdealData K x :=
  Classical.choice (exists_reducedPrincipalIdealData K x)

/-- The `c₄` invariant of an equation integral at `v` is integral at `v`.

This is the elementary polynomial part of the finite-place argument: all
coefficients occurring in `c₄` have valuation at most one, and a valuation is
nonarchimedean. -/
theorem IsIntegralAt.valuation_c₄_le_one
    {K : Type*} [Field K] [NumberField K]
    {v : HeightOneSpectrum (𝓞 K)} {W : WeierstrassCurve K}
    (h : IsIntegralAt K v W) :
    v.valuation K W.c₄ ≤ 1 := by
  let ν := v.valuation K
  have hconst (n : ℕ) : ν (n : K) ≤ 1 := by
    simpa using v.valuation_le_one (K := K) (n : 𝓞 K)
  have hb₂ : ν W.b₂ ≤ 1 := by
    rw [WeierstrassCurve.b₂]
    refine (ν.map_add _ _).trans (max_le ?_ ?_)
    · rw [map_pow]
      exact pow_le_one₀ bot_le h.a₁
    · rw [map_mul]
      exact mul_le_one₀ (hconst 4) bot_le h.a₂
  have hb₄ : ν W.b₄ ≤ 1 := by
    rw [WeierstrassCurve.b₄]
    refine (ν.map_add _ _).trans (max_le ?_ ?_)
    · rw [map_mul]
      exact mul_le_one₀ (hconst 2) bot_le h.a₄
    · rw [map_mul]
      exact mul_le_one₀ h.a₁ bot_le h.a₃
  rw [WeierstrassCurve.c₄]
  refine (ν.map_sub _ _).trans (max_le ?_ ?_)
  · rw [map_pow]
    exact pow_le_one₀ bot_le hb₂
  · rw [map_mul]
    exact mul_le_one₀ (hconst 24) bot_le hb₄

/-- Local minimality bounds the pole order of `j` by the minimal
discriminant exponent.

For the integral equation supplied by the certificate,
`j = Δ⁻¹ c₄³`; the preceding lemma bounds the `c₄` factor by one, while
the certificate identifies the discriminant valuation with `exp (-n)`. -/
theorem IsLocalMinimalDiscriminantExponent.valuation_j_le_exp
    {K : Type*} [Field K] [NumberField K]
    {v : HeightOneSpectrum (𝓞 K)} {W : WeierstrassCurve K}
    [W.IsElliptic] {n : ℕ}
    (h : IsLocalMinimalDiscriminantExponent K v W n) :
    v.valuation K W.j ≤ WithZero.exp (n : ℤ) := by
  rw [← W.variableChange_j h.change]
  let E := h.change • W
  let ν := v.valuation K
  have hc₄ : ν E.c₄ ≤ 1 := h.integral.valuation_c₄_le_one
  rw [WeierstrassCurve.j, map_mul, map_pow, Units.val_inv_eq_inv_val,
    map_inv₀, WeierstrassCurve.coe_Δ']
  change (ν E.Δ)⁻¹ * ν E.c₄ ^ 3 ≤ WithZero.exp (n : ℤ)
  rw [h.exponent, ← WithZero.exp_neg]
  simp only [neg_neg]
  exact mul_le_of_le_one_right bot_le (pow_le_one₀ bot_le hc₄)

end Heights
