/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
import Heights.LatticeAffinePoint
import Mathlib.GroupTheory.QuotientGroup.Defs

set_option linter.style.header false

/-!
# Set-theoretic descent of the lattice point map

For the explicit lattice curve attached to `τ`, this file extends the
point-valued Weierstrass map across its poles: lattice elements are sent to the
distinguished point at infinity, while every other complex number is sent to
`(℘(z), ℘'(z) / 2)`. Translation invariance then gives a set-theoretic map from
the additive quotient `ℂ / L`.

No topology or complex-analytic structure is put on this quotient map here. In
particular, this file does not prove continuity or analyticity at the poles,
compatibility with the elliptic-curve group law, bijectivity, or an
arbitrary-curve uniformization theorem.
-/

open scoped UpperHalfPlane

namespace Heights

/-- The total point-valued Weierstrass map: lattice elements are sent to the
point at infinity and non-lattice elements to `(℘, ℘' / 2)`. -/
noncomputable def latticePointMap (τ : ℍ) (z : ℂ) :
    (latticeWeierstrassCurve τ).toAffine.Point := by
  classical
  exact if hz : z ∈ (periodPairOfUpperHalfPlane τ).lattice then .zero
    else latticeAffinePoint τ z hz

/-- At a lattice element, the total map takes the distinguished point at
infinity. -/
@[simp] theorem latticePointMap_of_mem (τ : ℍ) (z : ℂ)
    (hz : z ∈ (periodPairOfUpperHalfPlane τ).lattice) :
    latticePointMap τ z = .zero := by
  classical
  simp [latticePointMap, hz]

/-- Away from the lattice, the total map agrees with the previously packaged
affine Weierstrass point. -/
@[simp] theorem latticePointMap_of_notMem (τ : ℍ) (z : ℂ)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice) :
    latticePointMap τ z = latticeAffinePoint τ z hz := by
  classical
  simp [latticePointMap, hz]

/-- The total point map is invariant under translation by any lattice element. -/
@[simp] theorem latticePointMap_add_lattice (τ : ℍ) (z : ℂ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    latticePointMap τ (z + l) = latticePointMap τ z := by
  classical
  by_cases hz : z ∈ (periodPairOfUpperHalfPlane τ).lattice
  · have hzl : z + (l : ℂ) ∈ (periodPairOfUpperHalfPlane τ).lattice :=
      (add_lattice_mem_iff τ z l).2 hz
    simp [latticePointMap, hz, hzl]
  · have hzl : z + (l : ℂ) ∉ (periodPairOfUpperHalfPlane τ).lattice :=
      (add_lattice_notMem_iff τ z l).2 hz
    simp [latticePointMap, hz, hzl, latticeAffinePoint_add_lattice]

/-- The additive quotient of `ℂ` by the lattice generated by `(τ, 1)`. -/
abbrev LatticeQuotient (τ : ℍ) :=
  ℂ ⧸ (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup

/-- The set-theoretic descent of `latticePointMap` through the lattice quotient. -/
noncomputable def latticeQuotientPointMap (τ : ℍ) :
    LatticeQuotient τ → (latticeWeierstrassCurve τ).toAffine.Point :=
  fun q ↦ Quotient.liftOn' q (latticePointMap τ) fun a b hab ↦ by
    rw [QuotientAddGroup.leftRel_apply] at hab
    let l : (periodPairOfUpperHalfPlane τ).lattice := ⟨-a + b, hab⟩
    simpa [l] using (latticePointMap_add_lattice τ a l).symm

/-- The descended map computes as the total point map on every quotient
representative. -/
@[simp] theorem latticeQuotientPointMap_mk (τ : ℍ) (z : ℂ) :
    latticeQuotientPointMap τ
        (QuotientAddGroup.mk'
          (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup z) =
      latticePointMap τ z := rfl

end Heights
