/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
import Heights.LatticeEisenstein
import Heights.ModularJ
import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Basic

set_option linter.style.header false

/-!
# The Weierstrass curve attached to an upper-half-plane lattice

For the period pair `(τ, 1)`, this file defines the short Weierstrass equation

`y² = x³ - g₂ x / 4 - g₃ / 4`.

Thus the pair `(℘(z), ℘'(z) / 2)` lies on the curve away from the lattice.  We
compute its algebraic discriminant and `j`-invariant exactly and identify the
latter with `Heights.modularJ τ`.

This is an explicit invariant computation only.  It does not descend `℘` to a
quotient torus, construct projective points at the lattice, prove a group-law
compatibility, or uniformize an arbitrary algebraic elliptic curve.
-/

open scoped UpperHalfPlane

namespace Heights

/-- The short Weierstrass curve attached to the lattice generated by `(τ, 1)`.
Its equation is `y² = x³ - g₂ x / 4 - g₃ / 4`, so the scaling
`y = ℘' / 2` matches mathlib's differential equation for `℘`. -/
noncomputable def latticeWeierstrassCurve (τ : ℍ) : WeierstrassCurve ℂ where
  a₁ := 0
  a₂ := 0
  a₃ := 0
  a₄ := -(periodPairOfUpperHalfPlane τ).g₂ / 4
  a₆ := -(periodPairOfUpperHalfPlane τ).g₃ / 4

@[simp] theorem latticeWeierstrassCurve_a₁ (τ : ℍ) :
    (latticeWeierstrassCurve τ).a₁ = 0 := rfl

@[simp] theorem latticeWeierstrassCurve_a₂ (τ : ℍ) :
    (latticeWeierstrassCurve τ).a₂ = 0 := rfl

@[simp] theorem latticeWeierstrassCurve_a₃ (τ : ℍ) :
    (latticeWeierstrassCurve τ).a₃ = 0 := rfl

@[simp] theorem latticeWeierstrassCurve_a₄ (τ : ℍ) :
    (latticeWeierstrassCurve τ).a₄ =
      -(periodPairOfUpperHalfPlane τ).g₂ / 4 := rfl

@[simp] theorem latticeWeierstrassCurve_a₆ (τ : ℍ) :
    (latticeWeierstrassCurve τ).a₆ =
      -(periodPairOfUpperHalfPlane τ).g₃ / 4 := rfl

/-- Away from the lattice poles, `(℘(z), ℘'(z) / 2)` satisfies the affine
Weierstrass equation of `latticeWeierstrassCurve τ`. -/
theorem weierstrassP_on_latticeWeierstrassCurve (τ : ℍ) (z : ℂ)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice) :
    (latticeWeierstrassCurve τ).toAffine.Equation
      ((periodPairOfUpperHalfPlane τ).weierstrassP z)
      ((periodPairOfUpperHalfPlane τ).derivWeierstrassP z / 2) := by
  rw [WeierstrassCurve.Affine.equation_iff]
  simp only [latticeWeierstrassCurve_a₁, latticeWeierstrassCurve_a₂,
    latticeWeierstrassCurve_a₃, latticeWeierstrassCurve_a₄,
    latticeWeierstrassCurve_a₆, zero_mul]
  have h := (periodPairOfUpperHalfPlane τ).derivWeierstrassP_sq z hz
  rw [div_pow]
  linear_combination h / 4

/-- The curve's `c₄` invariant is `12 g₂`. -/
theorem latticeWeierstrassCurve_c4 (τ : ℍ) :
    (latticeWeierstrassCurve τ).c₄ =
      12 * (periodPairOfUpperHalfPlane τ).g₂ := by
  simp [WeierstrassCurve.c₄, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    latticeWeierstrassCurve]
  ring

/-- The algebraic Weierstrass discriminant is exactly the classical lattice
invariant `g₂³ - 27g₃²`; there is no additional scaling factor. -/
theorem latticeWeierstrassCurve_discriminant (τ : ℍ) :
    (latticeWeierstrassCurve τ).Δ =
      (periodPairOfUpperHalfPlane τ).g₂ ^ 3 -
        27 * (periodPairOfUpperHalfPlane τ).g₃ ^ 2 := by
  simp [WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈, latticeWeierstrassCurve]
  ring

/-- Relative to mathlib's normalized modular discriminant, the curve
discriminant is `4096 π¹² Δ(τ)`. -/
theorem latticeWeierstrassCurve_discriminant_eq_modularDiscriminant (τ : ℍ) :
    (latticeWeierstrassCurve τ).Δ =
      4096 * (Real.pi : ℂ) ^ 12 * ModularForm.discriminant τ :=
  (latticeWeierstrassCurve_discriminant τ).trans
    (periodPair_invariant_discriminant τ)

/-- The lattice curve is elliptic because its explicitly computed
discriminant is nonzero. -/
noncomputable instance latticeWeierstrassCurve_isElliptic (τ : ℍ) :
    (latticeWeierstrassCurve τ).IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero,
    latticeWeierstrassCurve_discriminant]
  exact periodPair_invariant_discriminant_ne_zero τ

/-- The algebraic `j`-invariant of the lattice Weierstrass curve is the modular
`j`-function in the `q⁻¹ + 744 + ⋯` normalization. -/
theorem latticeWeierstrassCurve_j (τ : ℍ) :
    (latticeWeierstrassCurve τ).j = modularJ τ := by
  rw [WeierstrassCurve.j, Units.val_inv_eq_inv_val,
    WeierstrassCurve.coe_Δ']
  rw [latticeWeierstrassCurve_discriminant, latticeWeierstrassCurve_c4,
    periodPair_invariant_discriminant, periodPair_g₂, modularJ]
  field_simp [ModularForm.discriminant_ne_zero τ,
    Complex.ofReal_ne_zero.mpr Real.pi_ne_zero]
  ring

end Heights
