import Heights.LatticeQuotientPoint
import Mathlib.Topology.Algebra.Group.Quotient
import Mathlib.Topology.Covering.Quotient

set_option linter.style.header false

/-!
# Topology on the lattice quotient

This file records the topological-group structure that mathlib puts on the
additive quotient `ℂ / L` used by the lattice point map.  In particular, the
canonical quotient map is continuous, open, and a quotient map, and the
closedness of the period lattice makes the quotient a `T1Space`.

These are facts about the source quotient only.  No topology is put on the
elliptic-curve point type here, and no continuity, analyticity, group-law
compatibility, bijectivity, or uniformization property of
`latticeQuotientPointMap` is claimed.
-/

open Topology
open scoped UpperHalfPlane

noncomputable section

namespace Heights

/-- The canonical projection from `ℂ` to the additive quotient by the period
lattice generated by `(τ, 1)`. -/
abbrev latticeQuotientMk (τ : ℍ) : ℂ → LatticeQuotient τ :=
  QuotientAddGroup.mk'
    (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup

/-- The canonical projection to the lattice quotient is continuous. -/
@[fun_prop] theorem continuous_latticeQuotientMk (τ : ℍ) :
    Continuous (latticeQuotientMk τ) :=
  QuotientAddGroup.continuous_mk

/-- The canonical projection to the lattice quotient is an open map. -/
theorem isOpenMap_latticeQuotientMk (τ : ℍ) :
    IsOpenMap (latticeQuotientMk τ) :=
  QuotientAddGroup.isOpenMap_coe

/-- The canonical projection equips `ℂ / L` with the quotient topology. -/
theorem isQuotientMap_latticeQuotientMk (τ : ℍ) :
    Topology.IsQuotientMap (latticeQuotientMk τ) :=
  QuotientAddGroup.isQuotientMap_mk _

/-- The canonical projection is the quotient covering map for translation by
its discrete period lattice. This is the topological input used by
`Heights.LatticeQuotientManifold`; no manifold structure is asserted in this
file itself. -/
theorem isAddQuotientCoveringMap_latticeQuotientMk (τ : ℍ) :
    IsAddQuotientCoveringMap (latticeQuotientMk τ)
      (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup := by
  apply AddSubgroup.isAddQuotientCoveringMap_of_comm
  rw [isDiscrete_iff_discreteTopology]
  change DiscreteTopology (periodPairOfUpperHalfPlane τ).lattice
  infer_instance

/-- The canonical projection from `ℂ` to its period-lattice quotient is a
covering map. -/
theorem isCoveringMap_latticeQuotientMk (τ : ℍ) :
    IsCoveringMap (latticeQuotientMk τ) :=
  (isAddQuotientCoveringMap_latticeQuotientMk τ).isCoveringMap

/-- The lattice quotient is `T1` because a period lattice is closed in `ℂ`. -/
instance latticeQuotientT1Space (τ : ℍ) : T1Space (LatticeQuotient τ) :=
  QuotientAddGroup.t1Space_iff.mpr
    (periodPairOfUpperHalfPlane τ).isClosed_lattice

/-- Neighborhoods of a quotient class are the images of neighborhoods of any
chosen representative under the canonical projection. -/
theorem latticeQuotient_nhds_mk (τ : ℍ) (z : ℂ) :
    𝓝 (latticeQuotientMk τ z) = Filter.map (latticeQuotientMk τ) (𝓝 z) :=
  QuotientAddGroup.nhds_eq
    (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup z

end Heights
