import Heights.LatticeWeierstrass
import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point

set_option linter.style.header false

/-!
# The periodic affine Weierstrass point map away from a lattice

For the explicit lattice curve attached to `τ`, this file packages
`(℘(z), ℘'(z) / 2)` as an actual affine elliptic-curve point whenever `z` is
not in the period lattice. It then proves that translating `z` by a lattice
element preserves the domain and the packaged point.

This is only a map on the complement of the lattice. It does not assign the
point at infinity to lattice elements, descend a total map through `ℂ/L`, or
prove bijectivity, analyticity, or compatibility with the group law.
-/

open scoped UpperHalfPlane

namespace Heights

/-- The complement of the lattice generated by `(τ, 1)`. -/
abbrev LatticeComplement (τ : ℍ) :=
  {z : ℂ // z ∉ (periodPairOfUpperHalfPlane τ).lattice}

/-- Translation by a lattice element preserves the lattice complement. -/
def LatticeComplement.translate (τ : ℍ) (z : LatticeComplement τ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) : LatticeComplement τ :=
  ⟨z + l, fun h ↦ z.property <|
    (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup.add_mem_cancel_right l.2 |>.mp h⟩

@[simp] theorem LatticeComplement.coe_translate (τ : ℍ) (z : LatticeComplement τ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    (z.translate τ l : ℂ) = z + l := rfl

/-- The affine point `(℘(z), ℘'(z) / 2)` on the explicit lattice curve. -/
noncomputable def latticeAffinePoint (τ : ℍ) (z : ℂ)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice) :
    (latticeWeierstrassCurve τ).toAffine.Point :=
  WeierstrassCurve.Affine.Point.mk
    (weierstrassP_on_latticeWeierstrassCurve τ z hz)

/-- Both affine coordinates of `latticeAffinePoint`, expressed through
mathlib's point-to-coordinate equivalence. -/
@[simp] theorem latticeAffinePoint_pointEquiv (τ : ℍ) (z : ℂ)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice) :
    (latticeWeierstrassCurve τ).toAffine.pointEquiv
        (latticeAffinePoint τ z hz) =
      .some ⟨((periodPairOfUpperHalfPlane τ).weierstrassP z,
        (periodPairOfUpperHalfPlane τ).derivWeierstrassP z / 2),
        weierstrassP_on_latticeWeierstrassCurve τ z hz⟩ := by
  apply WeierstrassCurve.Affine.pointEquiv_some

/-- The affine-point map on the complement of the period lattice. -/
noncomputable def latticeAffinePointMap (τ : ℍ) :
    LatticeComplement τ → (latticeWeierstrassCurve τ).toAffine.Point :=
  fun z ↦ latticeAffinePoint τ z z.property

/-- Both affine coordinates of `latticeAffinePointMap`. -/
@[simp] theorem latticeAffinePointMap_pointEquiv (τ : ℍ) (z : LatticeComplement τ) :
    (latticeWeierstrassCurve τ).toAffine.pointEquiv
        (latticeAffinePointMap τ z) =
      .some ⟨((periodPairOfUpperHalfPlane τ).weierstrassP z,
        (periodPairOfUpperHalfPlane τ).derivWeierstrassP z / 2),
        weierstrassP_on_latticeWeierstrassCurve τ z z.property⟩ := by
  apply latticeAffinePoint_pointEquiv

@[simp] theorem add_lattice_mem_iff (τ : ℍ) (z : ℂ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    z + (l : ℂ) ∈ (periodPairOfUpperHalfPlane τ).lattice ↔
      z ∈ (periodPairOfUpperHalfPlane τ).lattice :=
  (periodPairOfUpperHalfPlane τ).lattice.toAddSubgroup.add_mem_cancel_right l.2

@[simp] theorem add_lattice_notMem_iff (τ : ℍ) (z : ℂ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    z + (l : ℂ) ∉ (periodPairOfUpperHalfPlane τ).lattice ↔
      z ∉ (periodPairOfUpperHalfPlane τ).lattice := by
  rw [not_congr (add_lattice_mem_iff τ z l)]

/-- Translation by a lattice element does not change the packaged affine
point. The two proof arguments merely certify that both inputs avoid poles. -/
@[simp] theorem latticeAffinePoint_add_lattice (τ : ℍ) (z : ℂ)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    latticeAffinePoint τ (z + l) ((add_lattice_notMem_iff τ z l).2 hz) =
      latticeAffinePoint τ z hz := by
  apply (latticeWeierstrassCurve τ).toAffine.pointEquiv.injective
  simp [latticeAffinePoint_pointEquiv]

/-- The complement-domain affine-point map is invariant under lattice
translation. This is periodicity on its natural pole-free domain, not yet a
quotient descent. -/
@[simp] theorem latticeAffinePointMap_translate (τ : ℍ) (z : LatticeComplement τ)
    (l : (periodPairOfUpperHalfPlane τ).lattice) :
    latticeAffinePointMap τ (z.translate τ l) = latticeAffinePointMap τ z := by
  apply (latticeWeierstrassCurve τ).toAffine.pointEquiv.injective
  simp [latticeAffinePointMap_pointEquiv]

end Heights
