import Mathlib.Analysis.SpecialFunctions.Elliptic.Weierstrass
import Mathlib.NumberTheory.ModularForms.EisensteinSeries.QExpansion
import Mathlib.NumberTheory.ModularForms.LevelOne.GradedRing

set_option linter.style.header false

/-!
# Lattice Eisenstein sums and normalized modular forms

This file connects mathlib's lattice invariants in `PeriodPair` to its
normalized level-one Eisenstein series.  For `τ` in the upper half-plane we
order the basis as `(τ, 1)`, so `PeriodPair.latticeEquivProd` matches the
integer-pair convention in `EisensteinSeries.eisSummand` directly.

Only the lattice-sum normalization is proved here.  No quotient torus,
uniformization map, or equivalence with an algebraic elliptic curve is claimed.
-/

open scoped UpperHalfPlane

namespace Heights

/-- The period pair `(τ, 1)` associated to a point of the upper half-plane.

The generated lattice is the usual lattice `ℤ + ℤτ`; the basis is ordered this
way to match mathlib's Eisenstein summand `m * τ + n`. -/
noncomputable def periodPairOfUpperHalfPlane (τ : ℍ) : PeriodPair where
  ω₁ := τ
  ω₂ := 1
  indep := LinearIndependent.pair_iff.mpr fun s t h ↦ by
    have hi := congrArg Complex.im h
    norm_num at hi
    have hs : s = 0 := hi.resolve_right τ.im_pos.ne'
    subst s
    norm_num at h
    exact ⟨rfl, h⟩

@[simp] theorem periodPairOfUpperHalfPlane_ω₁ (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).ω₁ = τ := rfl

@[simp] theorem periodPairOfUpperHalfPlane_ω₂ (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).ω₂ = 1 := rfl

open EisensteinSeries

/-- The lattice sum `PeriodPair.G` for `(τ, 1)` is the full Eisenstein sum over
integer pairs used by the modular-forms library. -/
theorem periodPair_G_eq_tsum_eisSummand (τ : ℍ) (k : ℕ) :
    (periodPairOfUpperHalfPlane τ).G k =
      ∑' v : Fin 2 → ℤ, eisSummand k v τ := by
  let L := periodPairOfUpperHalfPlane τ
  rw [PeriodPair.G, ← L.latticeEquivProd.symm.toEquiv.tsum_eq]
  rw [← (LinearEquiv.finTwoArrow ℤ ℤ).toEquiv.tsum_eq]
  apply tsum_congr
  intro v
  change ((↑(L.latticeEquivProd.symm (v 0, v 1)) : ℂ) ^ k)⁻¹ = eisSummand k v τ
  rw [PeriodPair.latticeEquiv_symm_apply]
  simp [L, periodPairOfUpperHalfPlane, eisSummand, zpow_neg]

/-- In every convergent weight, the lattice Eisenstein sum is twice the
Riemann-zeta value times mathlib's normalized level-one Eisenstein series. -/
theorem periodPair_G_eq_two_mul_riemannZeta_mul_E
    {k : ℕ} (hk : 3 ≤ k) (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).G k =
      2 * riemannZeta k * ModularForm.E hk τ := by
  rw [periodPair_G_eq_tsum_eisSummand,
    tsum_eisSummand_eq_riemannZeta_mul_eisensteinSeries hk τ]
  rw [show eisensteinSeries (N := 1) 0 k τ =
      2 * ModularForm.E hk τ by
    change eisensteinSeries (N := 1) 0 k τ =
      2 * ((1 / 2 : ℂ) * eisensteinSeries (N := 1) 0 k τ)
    ring]
  ring

private theorem riemannZeta_six :
    riemannZeta (6 : ℂ) = (Real.pi : ℂ) ^ 6 / 945 := by
  have h := riemannZeta_two_mul_nat (k := 3) (by norm_num : (3 : ℕ) ≠ 0)
  rw [show bernoulli 6 = 1 / 42 by decide +kernel] at h
  norm_num at h
  convert h using 1
  all_goals ring_nf

/-- Exact weight-four normalization for the lattice generated by `1` and `τ`. -/
theorem periodPair_G_four (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).G 4 =
      (Real.pi : ℂ) ^ 4 / 45 * ModularForm.E₄ τ := by
  rw [periodPair_G_eq_two_mul_riemannZeta_mul_E (by norm_num) τ]
  norm_num only [Nat.cast_ofNat]
  rw [riemannZeta_four]
  ring

/-- Exact weight-six normalization for the lattice generated by `1` and `τ`. -/
theorem periodPair_G_six (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).G 6 =
      (2 * (Real.pi : ℂ) ^ 6 / 945) * ModularForm.E₆ τ := by
  rw [periodPair_G_eq_two_mul_riemannZeta_mul_E (by norm_num) τ]
  norm_num only [Nat.cast_ofNat]
  rw [riemannZeta_six]
  ring

/-- Exact normalization of the lattice invariant `g₂ = 60 G₄`. -/
theorem periodPair_g₂ (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).g₂ =
      (4 * (Real.pi : ℂ) ^ 4 / 3) * ModularForm.E₄ τ := by
  rw [PeriodPair.g₂, periodPair_G_four]
  ring

/-- Exact normalization of the lattice invariant `g₃ = 140 G₆`. -/
theorem periodPair_g₃ (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).g₃ =
      (8 * (Real.pi : ℂ) ^ 6 / 27) * ModularForm.E₆ τ := by
  rw [PeriodPair.g₃, periodPair_G_six]
  ring

/-- The classical lattice discriminant has the exact normalization
`4096 π¹² Δ(τ)` relative to mathlib's modular discriminant. -/
theorem periodPair_invariant_discriminant (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).g₂ ^ 3 -
        27 * (periodPairOfUpperHalfPlane τ).g₃ ^ 2 =
      4096 * (Real.pi : ℂ) ^ 12 * ModularForm.discriminant τ := by
  rw [periodPair_g₂, periodPair_g₃,
    ModularForm.discriminant_eq_E₄_cube_sub_E₆_sq]
  ring

/-- The lattice discriminant of `(τ, 1)` is nonzero. -/
theorem periodPair_invariant_discriminant_ne_zero (τ : ℍ) :
    (periodPairOfUpperHalfPlane τ).g₂ ^ 3 -
        27 * (periodPairOfUpperHalfPlane τ).g₃ ^ 2 ≠ 0 := by
  rw [periodPair_invariant_discriminant]
  exact mul_ne_zero
    (mul_ne_zero (by norm_num)
      (pow_ne_zero _ (Complex.ofReal_ne_zero.mpr Real.pi_ne_zero)))
    (ModularForm.discriminant_ne_zero τ)

end Heights
