/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
import Heights.ArchimedeanAlgebraicRealization
import Mathlib.NumberTheory.ModularForms.EisensteinSeries.Summable

set_option linter.style.header false

/-!
# The `x`-coordinates of torsion points over `ℂ` are `O(N²)`

For an elliptic curve `W` over `ℂ` and an `N`-torsion point `P = (x, y) ∈ W(ℂ)`, the
`x`-coordinate satisfies

`‖x + b₂/12‖⁶ ≤ e^{C_Δ} · ‖Δ_W‖ · max(‖j_W‖, 1) · (2N² + B_j)⁶`

with `B_j = 80·S·(e^{C_y} log max(‖j_W‖, e) + 1)²` (`Heights.exists_torsion_x_bound`), where
`S = ∑_{x ∈ ℤ² ∖ 0} ‖x‖_∞^{−3}` and `C_Δ`, `C_y` are the absolute constants of the comparisons
`−log‖Δ(τ)‖ ≈ log max(‖j‖, 1)` and `log Im τ ≈ log log max(‖j‖, e)` on the fundamental domain
(`Heights.modularDeltaJ_fd_comparison`, `Heights.modularIm_logLogJ_fd_comparison`).

The proof uses the uniformization of the lattice curve `E_τ : y² = x³ − g₂x/4 − g₃/4`
(`Heights.latticeQuotientPointMapAddEquiv`) and the variable change `C` with `C • W = E_τ`
from same-`j` classification: `P` corresponds to `z ∈ ℂ` with `Nz ∈ L_τ`, and
`x = u²℘(z) + r` with `r = −b₂/12`, `u¹² = Δ_W/Δ(E_τ)`. Reducing `z = aτ + b` to
`|a|, |b| ≤ 1/2` gives `‖z‖² ≥ (a² + b²)/2 ≥ 1/(2N²)` on the fundamental domain, and the lattice
sum defining `℘` gives `‖℘(z)‖ ≤ 1/‖z‖² + 80‖τ‖²S` (`Heights.norm_weierstrassP_le`).
-/

open scoped UpperHalfPlane
open WeierstrassCurve

namespace Heights

/-! ### Lattice estimates on the fundamental domain -/

section Lattice

variable {τ : ℍ}

/-- On the fundamental domain, `‖aτ + b‖² ≥ (a² + b²)/2` for real `a, b`. -/
theorem normSq_mul_add_ge (hτ : τ ∈ ModularGroup.fd) (a b : ℝ) :
    (a ^ 2 + b ^ 2) / 2 ≤ Complex.normSq ((a : ℂ) * τ + b) := by
  obtain ⟨h1, h2⟩ := hτ
  have hre : |(τ : ℂ).re| ≤ 1 / 2 := h2
  have hns : 1 ≤ (τ : ℂ).re ^ 2 + (τ : ℂ).im ^ 2 := by
    simpa [Complex.normSq_apply, sq] using h1
  have hab : |2 * a * b * (τ : ℂ).re| ≤ |a * b| := by
    rw [show 2 * a * b * (τ : ℂ).re = (a * b) * (2 * (τ : ℂ).re) by ring, abs_mul]
    have : |2 * (τ : ℂ).re| ≤ 1 := by rw [abs_mul]; norm_num; linarith
    calc |a * b| * |2 * (τ : ℂ).re| ≤ |a * b| * 1 := by gcongr
      _ = |a * b| := mul_one _
  have hsq : 2 * |a * b| ≤ a ^ 2 + b ^ 2 := by
    rw [abs_mul]
    nlinarith [sq_nonneg (|a| - |b|), sq_abs a, sq_abs b]
  have heq : Complex.normSq ((a : ℂ) * τ + b) =
      a ^ 2 * ((τ : ℂ).re ^ 2 + (τ : ℂ).im ^ 2) + 2 * a * b * (τ : ℂ).re + b ^ 2 := by
    simp only [Complex.normSq_apply, Complex.add_re, Complex.mul_re, Complex.ofReal_re,
      Complex.ofReal_im, Complex.add_im, Complex.mul_im]
    ring
  rw [heq]
  have := neg_abs_le (2 * a * b * (τ : ℂ).re)
  nlinarith [sq_nonneg a]

/-- On the fundamental domain, `‖aτ + b‖ ≥ √((a² + b²)/2)`, in squared form. -/
theorem norm_mul_add_sq_ge (hτ : τ ∈ ModularGroup.fd) (a b : ℝ) :
    (a ^ 2 + b ^ 2) / 2 ≤ ‖(a : ℂ) * τ + b‖ ^ 2 := by
  rw [← Complex.normSq_eq_norm_sq]
  exact normSq_mul_add_ge hτ a b

/-- `1 ≤ ‖τ‖` on the fundamental domain. -/
theorem one_le_norm_of_mem_fd (hτ : τ ∈ ModularGroup.fd) : 1 ≤ ‖(τ : ℂ)‖ := by
  have h : 1 ≤ Complex.normSq (τ : ℂ) := hτ.1
  rw [Complex.normSq_eq_norm_sq] at h
  nlinarith [norm_nonneg (τ : ℂ)]

/-- `‖τ‖ ≤ Im τ + 1/2` on the fundamental domain. -/
theorem norm_le_im_add_half (hτ : τ ∈ ModularGroup.fd) : ‖(τ : ℂ)‖ ≤ τ.im + 1 / 2 := by
  have hre : |(τ : ℂ).re| ≤ 1 / 2 := hτ.2
  calc ‖(τ : ℂ)‖ ≤ |(τ : ℂ).re| + |(τ : ℂ).im| := Complex.norm_le_abs_re_add_abs_im _
    _ ≤ 1 / 2 + τ.im := by
      gcongr
      rw [UpperHalfPlane.coe_im, abs_of_pos τ.im_pos]
    _ = τ.im + 1 / 2 := add_comm _ _

/-- The absolute number `S = ∑_{x ∈ ℤ²} ‖x‖_∞^{−3}` (the term `x = 0` vanishes). -/
noncomputable def latticeSumThree : ℝ := ∑' x : Fin 2 → ℤ, ‖x‖ ^ (-3 : ℝ)

lemma summable_latticeSumThree : Summable fun x : Fin 2 → ℤ => ‖x‖ ^ (-3 : ℝ) :=
  EisensteinSeries.summable_one_div_norm_rpow (by norm_num)

lemma latticeSumThree_nonneg : 0 ≤ latticeSumThree :=
  tsum_nonneg fun _ => Real.rpow_nonneg (norm_nonneg _) _

/-- The coordinates of the lattice generated by `(τ, 1)`, as a map to `ℤ²`. -/
noncomputable def latticeCoords (τ : ℍ) : (periodPairOfUpperHalfPlane τ).lattice ≃ (Fin 2 → ℤ) :=
  (periodPairOfUpperHalfPlane τ).latticeEquivProd.toEquiv.trans (finTwoArrowEquiv ℤ).symm

lemma coe_eq_latticeCoords (l : (periodPairOfUpperHalfPlane τ).lattice) :
    (l : ℂ) = ((latticeCoords τ l 0 : ℤ) : ℂ) * τ + ((latticeCoords τ l 1 : ℤ) : ℂ) := by
  have h := (periodPairOfUpperHalfPlane τ).latticeEquiv_symm_apply
    ((periodPairOfUpperHalfPlane τ).latticeEquivProd l)
  rw [LinearEquiv.symm_apply_apply] at h
  rw [h]
  simp [latticeCoords]

/-- The bound for a single term of the lattice sum defining `℘` at a point `aτ + b` of the
fundamental parallelogram. -/
lemma norm_weierstrassP_term_le (hτ : τ ∈ ModularGroup.fd) {a b : ℝ} (ha : |a| ≤ 1 / 2)
    (hb : |b| ≤ 1 / 2) (l : (periodPairOfUpperHalfPlane τ).lattice)
    (hl : latticeCoords τ l ≠ 0) :
    ‖1 / ((a : ℂ) * τ + b - l) ^ 2 - 1 / (l : ℂ) ^ 2‖ ≤
      80 * ‖(τ : ℂ)‖ ^ 2 * ‖latticeCoords τ l‖ ^ (-3 : ℝ) := by
  set x := latticeCoords τ l with hx
  set m : ℤ := x 0
  set n : ℤ := x 1
  set s : ℝ := ‖x‖ with hs
  have hsmax : s = max (m.natAbs : ℝ) (n.natAbs : ℝ) := by
    rw [hs, EisensteinSeries.norm_eq_max_natAbs]; push_cast; rfl
  have hmax : max |(m : ℝ)| |(n : ℝ)| = s := by
    rw [hsmax, Nat.cast_natAbs, Nat.cast_natAbs, Int.cast_abs, Int.cast_abs]
  have hm : |(m : ℝ)| ≤ s := hmax ▸ le_max_left _ _
  have hn : |(n : ℝ)| ≤ s := hmax ▸ le_max_right _ _
  have hs1 : 1 ≤ s := by
    have : x ≠ 0 := hl
    rw [hsmax]
    have hmn : m ≠ 0 ∨ n ≠ 0 := by
      by_contra h
      rw [not_or, not_not, not_not] at h
      apply this
      funext i; fin_cases i
      · exact h.1
      · exact h.2
    rcases hmn with h | h
    · exact le_max_of_le_left (by exact_mod_cast Int.natAbs_pos.mpr h)
    · exact le_max_of_le_right (by exact_mod_cast Int.natAbs_pos.mpr h)
  have hs0 : 0 < s := by linarith
  have hlc : (l : ℂ) = (m : ℂ) * τ + n := coe_eq_latticeCoords l
  have hτ1 := one_le_norm_of_mem_fd hτ
  set z : ℂ := (a : ℂ) * τ + b with hz
  -- the lower bounds
  have hzl : s ^ 2 / 8 ≤ ‖z - l‖ ^ 2 := by
    have h := norm_mul_add_sq_ge hτ (a - m) (b - n)
    have heq : z - (l : ℂ) = ((a - m : ℝ) : ℂ) * τ + ((b - n : ℝ) : ℂ) := by
      rw [hz, hlc]; push_cast; ring
    rw [heq]
    refine le_trans ?_ h
    rcases le_total |(n : ℝ)| |(m : ℝ)| with hmn | hmn
    · have hms : |(m : ℝ)| = s := by rw [← hmax, max_eq_left hmn]
      have : s / 2 ≤ |a - m| := by
        have := abs_sub_abs_le_abs_sub (m : ℝ) a
        rw [abs_sub_comm] at this
        linarith
      nlinarith [sq_nonneg (b - n), abs_nonneg (a - m), sq_abs (a - m)]
    · have hns : |(n : ℝ)| = s := by rw [← hmax, max_eq_right hmn]
      have : s / 2 ≤ |b - n| := by
        have := abs_sub_abs_le_abs_sub (n : ℝ) b
        rw [abs_sub_comm] at this
        linarith
      nlinarith [sq_nonneg (a - m), abs_nonneg (b - n), sq_abs (b - n)]
  have hl2 : s ^ 2 / 2 ≤ ‖(l : ℂ)‖ ^ 2 := by
    have h := norm_mul_add_sq_ge hτ m n
    rw [hlc]
    push_cast at h
    refine le_trans ?_ h
    rcases le_total |(n : ℝ)| |(m : ℝ)| with hmn | hmn
    · have hms : |(m : ℝ)| = s := by rw [← hmax, max_eq_left hmn]
      nlinarith [sq_abs (m : ℝ), sq_nonneg (n : ℝ)]
    · have hns : |(n : ℝ)| = s := by rw [← hmax, max_eq_right hmn]
      nlinarith [sq_abs (n : ℝ), sq_nonneg (m : ℝ)]
  -- the upper bounds
  have hlup : ‖(l : ℂ)‖ ≤ 2 * s * ‖(τ : ℂ)‖ := by
    rw [hlc]
    calc ‖(m : ℂ) * τ + n‖ ≤ |(m : ℝ)| * ‖(τ : ℂ)‖ + |(n : ℝ)| := by
          refine (norm_add_le _ _).trans ?_
          rw [norm_mul]
          simp [Complex.norm_intCast]
      _ ≤ s * ‖(τ : ℂ)‖ + s * ‖(τ : ℂ)‖ := by gcongr; nlinarith
      _ = 2 * s * ‖(τ : ℂ)‖ := by ring
  have hzup : ‖z‖ ≤ ‖(τ : ℂ)‖ := by
    calc ‖z‖ ≤ |a| * ‖(τ : ℂ)‖ + |b| := by
          rw [hz]
          refine (norm_add_le _ _).trans ?_
          rw [norm_mul]
          simp [Complex.norm_real]
      _ ≤ 1 / 2 * ‖(τ : ℂ)‖ + 1 / 2 := by gcongr
      _ ≤ ‖(τ : ℂ)‖ := by linarith
  have hzl0 : z - l ≠ 0 := by
    intro h; rw [h, norm_zero] at hzl; nlinarith
  have hl0 : (l : ℂ) ≠ 0 := by
    intro h; rw [h, norm_zero] at hl2; nlinarith
  have hkey : 1 / (z - l) ^ 2 - 1 / (l : ℂ) ^ 2 = z * (2 * l - z) / ((z - l) ^ 2 * l ^ 2) := by
    field_simp; ring
  rw [hkey, norm_div, norm_mul, norm_mul, norm_pow, norm_pow]
  have h2l : ‖2 * (l : ℂ) - z‖ ≤ 5 * s * ‖(τ : ℂ)‖ := by
    calc ‖2 * (l : ℂ) - z‖ ≤ 2 * ‖(l : ℂ)‖ + ‖z‖ := by
          refine (norm_sub_le _ _).trans ?_; rw [norm_mul]; norm_num
      _ ≤ 2 * (2 * s * ‖(τ : ℂ)‖) + ‖(τ : ℂ)‖ := by gcongr
      _ ≤ 5 * s * ‖(τ : ℂ)‖ := by nlinarith
  have hrpow : ‖x‖ ^ (-3 : ℝ) = 1 / s ^ 3 := by
    rw [Real.rpow_neg (norm_nonneg _), ← hs]
    norm_num
  rw [hrpow, div_le_iff₀ (by positivity)]
  have hden : s ^ 4 / 16 ≤ ‖z - l‖ ^ 2 * ‖(l : ℂ)‖ ^ 2 := by
    have := mul_le_mul hzl hl2 (by positivity) (by positivity)
    nlinarith
  calc ‖z‖ * ‖2 * (l : ℂ) - z‖ ≤ ‖(τ : ℂ)‖ * (5 * s * ‖(τ : ℂ)‖) := by
        gcongr
    _ = 80 * ‖(τ : ℂ)‖ ^ 2 * (1 / s ^ 3) * (s ^ 4 / 16) := by field_simp; ring
    _ ≤ 80 * ‖(τ : ℂ)‖ ^ 2 * (1 / s ^ 3) * (‖z - l‖ ^ 2 * ‖(l : ℂ)‖ ^ 2) := by gcongr

/-- **The bound for `℘` on the fundamental parallelogram**: for `τ` in the fundamental domain and
`z = aτ + b ≠ 0` with `|a|, |b| ≤ 1/2`, `‖℘(z)‖ ≤ 1/‖z‖² + 80‖τ‖²S`. -/
theorem norm_weierstrassP_le (hτ : τ ∈ ModularGroup.fd) {a b : ℝ} (ha : |a| ≤ 1 / 2)
    (hb : |b| ≤ 1 / 2) :
    ‖(periodPairOfUpperHalfPlane τ).weierstrassP ((a : ℂ) * τ + b)‖ ≤
      1 / ‖(a : ℂ) * τ + b‖ ^ 2 + 80 * ‖(τ : ℂ)‖ ^ 2 * latticeSumThree := by
  classical
  set L := periodPairOfUpperHalfPlane τ
  set z : ℂ := (a : ℂ) * τ + b with hz
  set E := latticeCoords τ
  set f : L.lattice → ℂ := fun l => 1 / (z - l) ^ 2 - 1 / (l : ℂ) ^ 2 with hf
  set g : L.lattice → ℝ := fun l =>
    (if l = E.symm 0 then 1 / ‖z‖ ^ 2 else 0) + 80 * ‖(τ : ℂ)‖ ^ 2 * ‖E l‖ ^ (-3 : ℝ) with hg
  have hE0 : ((E.symm 0 : L.lattice) : ℂ) = 0 := by
    rw [coe_eq_latticeCoords]; simp [E]
  have hbound : ∀ l, ‖f l‖ ≤ g l := by
    intro l
    by_cases hl : l = E.symm 0
    · have hl' : (l : ℂ) = 0 := by rw [hl, hE0]
      have hEl : E l = 0 := by rw [hl, Equiv.apply_symm_apply]
      simp only [hf, hg, if_pos hl, hl', sub_zero, hEl, norm_zero]
      rw [Real.zero_rpow (by norm_num), mul_zero, add_zero]
      simp
    · have hEl : E l ≠ 0 := fun h => hl (by rw [← h, Equiv.symm_apply_apply])
      simp only [hf, hg, if_neg hl, zero_add]
      exact norm_weierstrassP_term_le hτ ha hb l hEl
  have hsg : Summable g := by
    refine Summable.add ?_ ?_
    · exact summable_of_hasFiniteSupport ((Set.finite_singleton (E.symm 0)).subset (by
        intro l hl; by_contra h; exact hl (if_neg h)))
    · exact (E.summable_iff.mpr summable_latticeSumThree).mul_left _
  have hsf : Summable fun l => ‖f l‖ :=
    Summable.of_nonneg_of_le (fun _ => norm_nonneg _) hbound hsg
  have htsum : ∑' l, g l = 1 / ‖z‖ ^ 2 + 80 * ‖(τ : ℂ)‖ ^ 2 * latticeSumThree := by
    rw [hg, Summable.tsum_add, tsum_ite_eq, tsum_mul_left]
    · congr 2
      exact E.tsum_eq (fun x => ‖x‖ ^ (-3 : ℝ))
    · exact summable_of_hasFiniteSupport ((Set.finite_singleton (E.symm 0)).subset (by
        intro l hl; by_contra h; exact hl (if_neg h)))
    · exact (E.summable_iff.mpr summable_latticeSumThree).mul_left _
  calc ‖L.weierstrassP z‖ = ‖∑' l, f l‖ := rfl
    _ ≤ ∑' l, ‖f l‖ := norm_tsum_le_tsum_norm hsf
    _ ≤ ∑' l, g l := Summable.tsum_le_tsum hbound hsf hsg
    _ = _ := htsum

/-- **The bound for `℘` at torsion points**: if `Nz ∈ L_τ` and `z ∉ L_τ` (`N ≥ 1`, `τ` in the
fundamental domain), then `‖℘(z)‖ ≤ 2N² + 80‖τ‖²S`. -/
theorem norm_weierstrassP_torsion_le (hτ : τ ∈ ModularGroup.fd) {N : ℕ} (hN : 1 ≤ N) {z : ℂ}
    (hNz : (N : ℂ) * z ∈ (periodPairOfUpperHalfPlane τ).lattice)
    (hz : z ∉ (periodPairOfUpperHalfPlane τ).lattice) :
    ‖(periodPairOfUpperHalfPlane τ).weierstrassP z‖ ≤
      2 * N ^ 2 + 80 * ‖(τ : ℂ)‖ ^ 2 * latticeSumThree := by
  set L := periodPairOfUpperHalfPlane τ
  obtain ⟨m, n, hmn⟩ := PeriodPair.mem_lattice.mp hNz
  have hN0 : (N : ℝ) ≠ 0 := by positivity
  set a₀ : ℝ := m / N
  set b₀ : ℝ := n / N
  set k : ℤ := round a₀
  set k' : ℤ := round b₀
  set a : ℝ := a₀ - k
  set b : ℝ := b₀ - k'
  have ha : |a| ≤ 1 / 2 := abs_sub_round a₀
  have hb : |b| ≤ 1 / 2 := abs_sub_round b₀
  have hzab : z = ((a : ℂ) * τ + b) + ((k : ℂ) * τ + k') := by
    have hN0' : (N : ℂ) ≠ 0 := by exact_mod_cast hN0
    have : z = (m / N : ℂ) * τ + (n / N : ℂ) := by
      field_simp
      have h2 : (periodPairOfUpperHalfPlane τ).ω₂ = 1 := rfl
      rw [h2, mul_one] at hmn
      rw [mul_comm, ← hmn]
      rfl
    rw [this]
    simp only [a, b, a₀, b₀]
    push_cast
    ring
  have hkmem : ((k : ℂ) * τ + k') ∈ L.lattice :=
    PeriodPair.mem_lattice.mpr ⟨k, k', by simp [L, periodPairOfUpperHalfPlane]⟩
  have hP : L.weierstrassP z = L.weierstrassP ((a : ℂ) * τ + b) := by
    rw [hzab]
    exact L.weierstrassP_add_coe _ ⟨_, hkmem⟩
  rw [hP]
  refine (norm_weierstrassP_le hτ ha hb).trans ?_
  gcongr
  -- `1/‖aτ + b‖² ≤ 2N²`
  have hNa : (N : ℝ) * a = m - N * k := by simp only [a, a₀]; field_simp
  have hNb : (N : ℝ) * b = n - N * k' := by simp only [b, b₀]; field_simp
  have hab : (1 : ℝ) ≤ (N * a) ^ 2 + (N * b) ^ 2 := by
    rw [hNa, hNb]
    have hne : m - N * k ≠ 0 ∨ n - N * k' ≠ 0 := by
      by_contra h
      rw [not_or, not_not, not_not] at h
      apply hz
      have ha0 : a = 0 := by
        have : (N : ℝ) * a = 0 := by rw [hNa]; exact_mod_cast h.1
        exact (mul_eq_zero.mp this).resolve_left hN0
      have hb0 : b = 0 := by
        have : (N : ℝ) * b = 0 := by rw [hNb]; exact_mod_cast h.2
        exact (mul_eq_zero.mp this).resolve_left hN0
      rw [hzab, ha0, hb0]
      simpa using hkmem
    rcases hne with h | h
    · have : (1 : ℝ) ≤ ((m - N * k : ℤ) : ℝ) ^ 2 := by
        have := Int.one_le_abs h
        have h' : (1 : ℝ) ≤ |((m - N * k : ℤ) : ℝ)| := by exact_mod_cast this
        nlinarith [sq_abs ((m - N * k : ℤ) : ℝ)]
      push_cast at this
      nlinarith [sq_nonneg ((n : ℝ) - N * k')]
    · have : (1 : ℝ) ≤ ((n - N * k' : ℤ) : ℝ) ^ 2 := by
        have := Int.one_le_abs h
        have h' : (1 : ℝ) ≤ |((n - N * k' : ℤ) : ℝ)| := by exact_mod_cast this
        nlinarith [sq_abs ((n - N * k' : ℤ) : ℝ)]
      push_cast at this
      nlinarith [sq_nonneg ((m : ℝ) - N * k)]
  have hlow := norm_mul_add_sq_ge hτ a b
  have hpos : 0 < ‖(a : ℂ) * τ + b‖ ^ 2 := by
    have : 0 < (a ^ 2 + b ^ 2) / 2 := by
      have : 0 < (N : ℝ) ^ 2 * (a ^ 2 + b ^ 2) := by nlinarith
      have := pos_of_mul_pos_right this (by positivity)
      positivity
    linarith
  rw [div_le_iff₀ hpos]
  have : (1 : ℝ) ≤ N ^ 2 * (a ^ 2 + b ^ 2) := by nlinarith
  nlinarith

end Lattice

/-! ### Torsion points of the lattice curve -/

/-- An affine `N`-torsion point of a curve equal to the lattice curve `E_τ` has `x`-coordinate
`℘(z)` for some `z ∉ L_τ` with `Nz ∈ L_τ`. -/
theorem exists_weierstrassP_of_torsion {τ : ℍ} {W' : WeierstrassCurve ℂ}
    (hW' : W' = latticeWeierstrassCurve τ) {N : ℕ} {x y : ℂ}
    (h : W'.toAffine.Nonsingular x y)
    (hP : N • (Affine.Point.some x y h : W'.toAffine.Point) = 0) :
    ∃ z : ℂ, z ∉ (periodPairOfUpperHalfPlane τ).lattice ∧
      (N : ℂ) * z ∈ (periodPairOfUpperHalfPlane τ).lattice ∧
      x = (periodPairOfUpperHalfPlane τ).weierstrassP z := by
  classical
  subst hW'
  set e := latticeQuotientPointMapAddEquiv τ
  obtain ⟨z, hz⟩ := QuotientAddGroup.mk_surjective (e.symm (Affine.Point.some x y h))
  have hez : e (QuotientAddGroup.mk z) = Affine.Point.some x y h := by
    rw [hz, AddEquiv.apply_symm_apply]
  have hmap : e (QuotientAddGroup.mk z) = latticePointMap τ z := rfl
  have hzL : z ∉ (periodPairOfUpperHalfPlane τ).lattice := by
    intro hzL
    rw [hmap, latticePointMap_of_mem τ z hzL] at hez
    exact Affine.Point.some_ne_zero h hez.symm
  refine ⟨z, hzL, ?_, ?_⟩
  · have h0 : e (N • (QuotientAddGroup.mk z : LatticeQuotient τ)) = 0 := by
      rw [map_nsmul, hez, hP]
    have h1 : N • (QuotientAddGroup.mk z : LatticeQuotient τ) = 0 :=
      e.injective (h0.trans (map_zero e).symm)
    rw [← QuotientAddGroup.mk_nsmul, QuotientAddGroup.eq_zero_iff] at h1
    simpa [nsmul_eq_mul] using h1
  · rw [hmap, latticePointMap_of_notMem τ z hzL, latticeAffinePoint] at hez
    exact (Affine.Point.some.inj hez).1.symm

/-- **The `x`-coordinate of an `N`-torsion point through a variable change to a lattice
curve**: if `C • W = E_τ` with `τ` in the fundamental domain, an affine `N`-torsion point `(x, y)`
of `W` satisfies `‖x − r‖ ≤ ‖u‖²(2N² + 80‖τ‖²S)`. -/
theorem norm_x_sub_r_le {W : WeierstrassCurve ℂ} [W.IsElliptic] {τ : ℍ} (hτ : τ ∈ ModularGroup.fd)
    {C : VariableChange ℂ} (hC : C • W = latticeWeierstrassCurve τ) {N : ℕ} (hN : 1 ≤ N)
    {x y : ℂ} (h : W.toAffine.Nonsingular x y)
    (hP : N • (Affine.Point.some x y h : W.toAffine.Point) = 0) :
    ‖x - C.r‖ ≤ ‖(C.u : ℂ)‖ ^ 2 * (2 * N ^ 2 + 80 * ‖(τ : ℂ)‖ ^ 2 * latticeSumThree) := by
  classical
  set P' := (C.pointAddEquiv W).symm (Affine.Point.some x y h) with hP'
  have hP'0 : N • P' = 0 := by rw [hP', ← map_nsmul, hP, map_zero]
  have hP'eq : P' = C.inversePointMap W (Affine.Point.some x y h) := rfl
  rw [VariableChange.inversePointMap_some] at hP'eq
  rw [hP'eq] at hP'0
  obtain ⟨z, hzL, hNz, hx⟩ := exists_weierstrassP_of_torsion hC _ hP'0
  have hxr : x - C.r = (C.u : ℂ) ^ 2 * (periodPairOfUpperHalfPlane τ).weierstrassP z := by
    rw [← hx, VariableChange.inverseX]
    field_simp [Units.ne_zero]
  rw [hxr, norm_mul, norm_pow]
  gcongr
  exact norm_weierstrassP_torsion_le hτ hN hNz hzL

/-- **The `x`-coordinates of `N`-torsion points over `ℂ` are `O(N²)`**, with explicit dependence
on the curve: `‖x + b₂/12‖⁶ ≤ A·‖Δ‖·max(‖j‖, 1)·(2N² + B(log max(‖j‖, e) + 1)²)⁶` for absolute
constants `A, B ≥ 0`. -/
theorem exists_torsion_x_bound :
    ∃ A B : ℝ, 0 ≤ A ∧ 0 ≤ B ∧ ∀ (W : WeierstrassCurve ℂ) [W.IsElliptic] {N : ℕ}, 1 ≤ N →
      ∀ {x y : ℂ} (h : W.toAffine.Nonsingular x y),
        N • (Affine.Point.some x y h : W.toAffine.Point) = 0 →
        ‖x + W.b₂ / 12‖ ^ 6 ≤ A * ‖W.Δ‖ * max ‖W.j‖ 1 *
          (2 * N ^ 2 + B * (Real.log (max ‖W.j‖ (Real.exp 1)) + 1) ^ 2) ^ 6 := by
  obtain ⟨CΔ, hCΔ0, hCΔ⟩ := modularDeltaJ_fd_comparison
  obtain ⟨Cy, hCy0, hCy⟩ := modularIm_logLogJ_fd_comparison
  refine ⟨Real.exp CΔ, 80 * latticeSumThree * Real.exp Cy ^ 2, (Real.exp_pos _).le,
    by have := latticeSumThree_nonneg; positivity, ?_⟩
  intro W _ N hN x y h hP
  obtain ⟨τ, hτ, hτj⟩ := exists_mem_fd_modularJ_eq_of_surjective modularJ_surjective W.j
  obtain ⟨C, hC⟩ := W.exists_variableChange_of_j_eq (latticeWeierstrassCurve τ)
    (by rw [latticeWeierstrassCurve_j, hτj])
  have hr : C.r = -(W.b₂ / 12) := by
    have hb := variableChange_b₂ W C
    rw [hC] at hb
    have h0 : (latticeWeierstrassCurve τ).b₂ = 0 := by
      simp [WeierstrassCurve.b₂, latticeWeierstrassCurve]
    rw [h0] at hb
    have hu : ((C.u⁻¹ : ℂˣ) : ℂ) ^ 2 ≠ 0 := pow_ne_zero _ (Units.ne_zero _)
    have := (mul_eq_zero.mp hb.symm).resolve_left hu
    linear_combination this / 12
  have hΔ : ‖(C.u : ℂ)‖ ^ 12 * ‖(latticeWeierstrassCurve τ).Δ‖ = ‖W.Δ‖ := by
    have hd := variableChange_Δ W C
    rw [hC] at hd
    rw [hd, norm_mul, ← mul_assoc, ← norm_pow, ← norm_mul, ← mul_pow, Units.val_inv_eq_inv_val,
      mul_inv_cancel₀ (Units.ne_zero C.u), one_pow, norm_one, one_mul]
  have hlat : (latticeWeierstrassCurve τ).Δ = silvermanModularDiscriminant τ := by
    rw [latticeWeierstrassCurve_discriminant_eq_modularDiscriminant, silvermanModularDiscriminant]
    ring
  have hj : modularJ τ = W.j := hτj
  -- the lower bound for the lattice discriminant
  have hΔlow : 1 ≤ Real.exp CΔ * max ‖W.j‖ 1 * ‖(latticeWeierstrassCurve τ).Δ‖ := by
    have h1 := hCΔ τ hτ
    rw [hj] at h1
    have hpos : 0 < ‖silvermanModularDiscriminant τ‖ := silvermanModularDiscriminant_norm_pos τ
    have hM : 0 < max ‖W.j‖ 1 := lt_max_of_lt_right one_pos
    have h2 : Real.log (1 / (max ‖W.j‖ 1 * ‖silvermanModularDiscriminant τ‖)) ≤ CΔ := by
      rw [one_div, Real.log_inv, Real.log_mul hM.ne' hpos.ne']
      linarith [(abs_le.mp h1).2]
    have h3 := Real.exp_le_exp.mpr h2
    rw [Real.exp_log (by positivity)] at h3
    rw [hlat]
    rw [div_le_iff₀ (by positivity)] at h3
    linarith
  -- the bound for `‖τ‖`
  have hτnorm : ‖(τ : ℂ)‖ ^ 2 ≤ Real.exp Cy ^ 2 *
      (Real.log (max ‖W.j‖ (Real.exp 1)) + 1) ^ 2 := by
    have h1 := hCy τ hτ
    rw [hj] at h1
    have hL : 1 ≤ Real.log (max ‖W.j‖ (Real.exp 1)) := by
      rw [Real.le_log_iff_exp_le (lt_max_of_lt_right (Real.exp_pos 1))]
      exact le_max_right _ _
    have him : τ.im ≤ Real.exp Cy * Real.log (max ‖W.j‖ (Real.exp 1)) := by
      have h2 : Real.log τ.im ≤ Cy + Real.log (Real.log (max ‖W.j‖ (Real.exp 1))) := by
        linarith [(abs_le.mp h1).2]
      have h3 := Real.exp_le_exp.mpr h2
      rw [Real.exp_log τ.im_pos, Real.exp_add, Real.exp_log (by linarith)] at h3
      exact h3
    have hn := norm_le_im_add_half hτ
    have hn0 : 0 ≤ ‖(τ : ℂ)‖ := norm_nonneg _
    have hle : ‖(τ : ℂ)‖ ≤ Real.exp Cy * (Real.log (max ‖W.j‖ (Real.exp 1)) + 1) := by
      have : 1 ≤ Real.exp Cy := Real.one_le_exp hCy0
      nlinarith
    calc ‖(τ : ℂ)‖ ^ 2 ≤ (Real.exp Cy * (Real.log (max ‖W.j‖ (Real.exp 1)) + 1)) ^ 2 := by
          gcongr
      _ = _ := by ring
  have hmain := norm_x_sub_r_le hτ hC hN h hP
  rw [hr, sub_neg_eq_add] at hmain
  set Q : ℝ := 2 * N ^ 2 + 80 * ‖(τ : ℂ)‖ ^ 2 * latticeSumThree with hQ
  set Q' : ℝ := 2 * N ^ 2 + 80 * latticeSumThree * Real.exp Cy ^ 2 *
    (Real.log (max ‖W.j‖ (Real.exp 1)) + 1) ^ 2 with hQ'
  have hQle : Q ≤ Q' := by
    have := latticeSumThree_nonneg
    rw [hQ, hQ']
    nlinarith
  have hQ0 : 0 ≤ Q := by have := latticeSumThree_nonneg; positivity
  have h6 : ‖x + W.b₂ / 12‖ ^ 6 ≤ ‖(C.u : ℂ)‖ ^ 12 * Q ^ 6 := by
    calc ‖x + W.b₂ / 12‖ ^ 6 ≤ (‖(C.u : ℂ)‖ ^ 2 * Q) ^ 6 := by gcongr
      _ = ‖(C.u : ℂ)‖ ^ 12 * Q ^ 6 := by ring
  calc ‖x + W.b₂ / 12‖ ^ 6 ≤ ‖(C.u : ℂ)‖ ^ 12 * Q ^ 6 := h6
    _ ≤ ‖(C.u : ℂ)‖ ^ 12 * (Real.exp CΔ * max ‖W.j‖ 1 * ‖(latticeWeierstrassCurve τ).Δ‖) *
        Q ^ 6 := by
      have : 0 ≤ ‖(C.u : ℂ)‖ ^ 12 * Q ^ 6 := by positivity
      nlinarith
    _ = Real.exp CΔ * ‖W.Δ‖ * max ‖W.j‖ 1 * Q ^ 6 := by rw [← hΔ]; ring
    _ ≤ Real.exp CΔ * ‖W.Δ‖ * max ‖W.j‖ 1 * Q' ^ 6 := by gcongr
    _ = _ := by rw [hQ']

end Heights
