import Heights.Absolute.Extension

set_option linter.style.header false

/-!
# The absolute logarithmic Weil height on `ℚ̄`

For a finite family `x : ι → ℚ̄` (homogeneous coordinates of a point of projective space) we
define the absolute logarithmic Weil height `Heights.Absolute.logHeight x` as Mathlib's
relative height `Height.logHeight` of `x`, viewed in the number field `ℚ(x) ⊆ ℚ̄` generated by
its coordinates, divided by `[ℚ(x) : ℚ]`.

The main result is the independence of the choice of field of definition
(`Heights.Absolute.logHeight_comp_ringHom`): for any number field `L`, ring hom
`φ : L →+* ℚ̄` and `y : ι → L`, `logHeight (φ ∘ y) = h_L(y) / [L : ℚ]`.  It follows from the
extension formula `h_K(y) = [K : k] · h_k(y)` of `Heights.Absolute.Extension`.

We then derive the basic properties: nonnegativity, invariance under scaling, under ring
endomorphisms of `ℚ̄` (Galois invariance), under reindexing and adding zero coordinates, the
Segre (multiplicativity) identity, the formula `logHeight ![1, a] = h_{ℚ(a)}(a) / [ℚ(a) : ℚ]`,
invariance under `a ↦ a⁻¹`, the estimate for translations, and the local formula.
-/

namespace Heights.Absolute

open NumberField Module IntermediateField
open scoped IntermediateField

/-- The algebraic closure `ℚ̄` of `ℚ`. -/
abbrev Qbar := AlgebraicClosure ℚ

/-- Every element of `ℚ̄` is integral over `ℚ`. -/
theorem isIntegral (a : Qbar) : IsIntegral ℚ a :=
  (AlgebraicClosure.isAlgebraic ℚ |>.isAlgebraic a).isIntegral

/-- A finite-dimensional intermediate field of `ℚ̄` is a number field. -/
instance (F : IntermediateField ℚ Qbar) [FiniteDimensional ℚ F] : NumberField F where

/-- The field generated by finitely many elements of `ℚ̄` is finite-dimensional. -/
instance finiteDimensional_adjoin (S : Set Qbar) [Finite S] :
    FiniteDimensional ℚ (IntermediateField.adjoin ℚ S) :=
  IntermediateField.finiteDimensional_adjoin fun a _ => isIntegral a

variable {ι κ : Type*}

/-- The field of definition `ℚ(x)` generated by the coordinates of `x`. -/
noncomputable abbrev fieldOf (x : ι → Qbar) : IntermediateField ℚ Qbar :=
  IntermediateField.adjoin ℚ (Set.range x)

/-- The coordinates of `x`, viewed in `ℚ(x)`. -/
noncomputable def coords (x : ι → Qbar) : ι → fieldOf x :=
  fun i => ⟨x i, IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩⟩

@[simp]
lemma coe_coords (x : ι → Qbar) (i : ι) : (coords x i : Qbar) = x i := rfl

variable [Finite ι] [Finite κ]

/-- **The absolute logarithmic Weil height** of the point of projective space with homogeneous
coordinates `x` (it is `0` for `x = 0`): the relative height of `x` in `ℚ(x)` divided by the
degree `[ℚ(x) : ℚ]`. -/
noncomputable def logHeight (x : ι → Qbar) : ℝ :=
  Height.logHeight (coords x) / finrank ℚ (fieldOf x)

/-- **Independence of the field of definition**: for any number field `L`, embedding
`φ : L →+* ℚ̄` and `y : ι → L`, the absolute height of `φ ∘ y` is `h_L(y) / [L : ℚ]`. -/
theorem logHeight_comp_ringHom {L : Type*} [Field L] [NumberField L] (φ : L →+* Qbar)
    (y : ι → L) : logHeight (fun i => φ (y i)) = Height.logHeight y / finrank ℚ L := by
  set x : ι → Qbar := fun i => φ (y i) with hx
  set M : IntermediateField ℚ Qbar := φ.toRatAlgHom.fieldRange
  let g : L ≃ₐ[ℚ] M := AlgEquiv.ofInjectiveField φ.toRatAlgHom
  have : FiniteDimensional ℚ M := g.toLinearEquiv.finiteDimensional
  have hle : fieldOf x ≤ M := by
    rw [IntermediateField.adjoin_le_iff]
    rintro _ ⟨i, rfl⟩
    exact ⟨y i, rfl⟩
  have h1 := Heights.Absolute.logHeight_comp_ringHom_div_finrank
    (IntermediateField.inclusion hle).toRingHom (coords x)
  have h2 := Heights.Absolute.logHeight_comp_ringHom_div_finrank g.toRingEquiv.toRingHom y
  have hcomp : (fun i => (IntermediateField.inclusion hle).toRingHom (coords x i)) =
      fun i => g.toRingEquiv.toRingHom (y i) := by
    ext i
    rfl
  rw [logHeight, ← h1, hcomp, h2]

/-- `logHeight_comp_ringHom` stated for `x = φ ∘ y`. -/
theorem logHeight_eq_of_eq_comp {L : Type*} [Field L] [NumberField L] (φ : L →+* Qbar)
    {x : ι → Qbar} {y : ι → L} (h : x = φ ∘ y) :
    logHeight x = Height.logHeight y / finrank ℚ L := by
  subst h
  exact logHeight_comp_ringHom φ y

/-- The absolute height computed in any finite-dimensional intermediate field containing the
coordinates. -/
theorem logHeight_eq_of_mem (F : IntermediateField ℚ Qbar) [FiniteDimensional ℚ F]
    (y : ι → F) : logHeight (fun i => (y i : Qbar)) = Height.logHeight y / finrank ℚ F :=
  logHeight_comp_ringHom F.val.toRingHom y

/-- The absolute height computed in any finite-dimensional intermediate field containing the
coordinates, with an explicit membership proof. -/
theorem logHeight_eq_of_forall_mem {x : ι → Qbar} (F : IntermediateField ℚ Qbar)
    [FiniteDimensional ℚ F] (hx : ∀ i, x i ∈ F) :
    logHeight x = Height.logHeight (fun i => (⟨x i, hx i⟩ : F)) / finrank ℚ F :=
  logHeight_eq_of_mem F (fun i => ⟨x i, hx i⟩)

/-! ### Basic properties -/

lemma finrank_pos_real (F : IntermediateField ℚ Qbar) [FiniteDimensional ℚ F] :
    (0 : ℝ) < finrank ℚ F :=
  Nat.cast_pos.mpr finrank_pos

theorem logHeight_nonneg (x : ι → Qbar) : 0 ≤ logHeight x :=
  div_nonneg (Height.logHeight_nonneg _) (Nat.cast_nonneg _)

@[simp]
theorem logHeight_zero : logHeight (0 : ι → Qbar) = 0 := by
  have : coords (0 : ι → Qbar) = 0 := by
    ext i
    rfl
  rw [logHeight, this, Height.logHeight_zero, zero_div]

/-- Invariance under scaling by a nonzero constant. -/
theorem logHeight_smul (x : ι → Qbar) {c : Qbar} (hc : c ≠ 0) :
    logHeight (c • x) = logHeight x := by
  set F := IntermediateField.adjoin ℚ (insert c (Set.range x))
  have hcF : c ∈ F := IntermediateField.subset_adjoin _ _ (Set.mem_insert _ _)
  have hxF : ∀ i, x i ∈ F := fun i =>
    IntermediateField.subset_adjoin _ _ (Set.mem_insert_of_mem _ ⟨i, rfl⟩)
  have hcxF : ∀ i, (c • x) i ∈ F := fun i => F.mul_mem hcF (hxF i)
  rw [logHeight_eq_of_forall_mem F hxF, logHeight_eq_of_forall_mem F hcxF]
  have hc' : (⟨c, hcF⟩ : F) ≠ 0 := fun h => hc (congrArg Subtype.val h)
  rw [← Height.logHeight_smul_eq_logHeight (fun i => (⟨x i, hxF i⟩ : F)) hc']
  rfl

/-- **Galois invariance**: the height is invariant under every ring endomorphism of `ℚ̄`. -/
theorem logHeight_comp_ringHom_self (σ : Qbar →+* Qbar) (x : ι → Qbar) :
    logHeight (fun i => σ (x i)) = logHeight x :=
  logHeight_comp_ringHom (σ.comp (fieldOf x).val.toRingHom) (coords x)

/-- Invariance under reindexing. -/
theorem logHeight_comp_equiv (e : κ ≃ ι) (x : ι → Qbar) :
    logHeight (x ∘ e) = logHeight x := by
  change logHeight (fun j => x (e j)) = _
  have hx : ∀ i, x i ∈ fieldOf x := fun i => (coords x i).2
  rw [logHeight_eq_of_forall_mem (fieldOf x) (fun j => hx (e j)), logHeight]
  exact congrArg (· / _) (Height.logHeight_comp_equiv e (coords x))

/-- Adding zero coordinates does not change the height. -/
theorem logHeight_sumElim_zero (x : ι → Qbar) :
    logHeight (Sum.elim x (0 : κ → Qbar)) = logHeight x := by
  have hx : ∀ i, Sum.elim x (0 : κ → Qbar) i ∈ fieldOf x := by
    rintro (i | j)
    · exact (coords x i).2
    · exact (fieldOf x).zero_mem
  rw [logHeight_eq_of_forall_mem (fieldOf x) hx, logHeight,
    ← Height.logHeight_sumElim_zero_eq (ι' := κ) (coords x)]
  congr 2
  ext (i | j) <;> rfl

/-- Forgetting coordinates can only decrease the height. -/
theorem logHeight_comp_le (f : κ → ι) (x : ι → Qbar) :
    logHeight (x ∘ f) ≤ logHeight x := by
  change logHeight (fun j => x (f j)) ≤ _
  have hx : ∀ i, x i ∈ fieldOf x := fun i => (coords x i).2
  rw [logHeight_eq_of_forall_mem (fieldOf x) (fun j => hx (f j)), logHeight]
  exact div_le_div_of_nonneg_right (Height.logHeight_comp_le f (coords x)) (Nat.cast_nonneg _)

/-- **Segre identity**: the height of the multiplication table `x_i y_j` is the sum of the
heights. -/
theorem logHeight_mul_table {x : ι → Qbar} (hx : x ≠ 0) {y : κ → Qbar} (hy : y ≠ 0) :
    logHeight (fun p : ι × κ => x p.1 * y p.2) = logHeight x + logHeight y := by
  set F := IntermediateField.adjoin ℚ (Set.range x ∪ Set.range y)
  have hxF : ∀ i, x i ∈ F := fun i =>
    IntermediateField.subset_adjoin _ _ (Or.inl ⟨i, rfl⟩)
  have hyF : ∀ j, y j ∈ F := fun j =>
    IntermediateField.subset_adjoin _ _ (Or.inr ⟨j, rfl⟩)
  have hxyF : ∀ p : ι × κ, x p.1 * y p.2 ∈ F := fun p => F.mul_mem (hxF p.1) (hyF p.2)
  rw [logHeight_eq_of_forall_mem F hxF, logHeight_eq_of_forall_mem F hyF,
    logHeight_eq_of_forall_mem F hxyF, ← add_div]
  have hx' : (fun i => (⟨x i, hxF i⟩ : F)) ≠ 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hx
    exact Function.ne_iff.mpr ⟨i, fun h => hi (congrArg Subtype.val h)⟩
  have hy' : (fun j => (⟨y j, hyF j⟩ : F)) ≠ 0 := by
    obtain ⟨j, hj⟩ := Function.ne_iff.mp hy
    exact Function.ne_iff.mpr ⟨j, fun h => hj (congrArg Subtype.val h)⟩
  rw [← Height.logHeight_fun_mul_eq hx' hy']
  rfl

/-! ### Heights of elements of `ℚ̄` -/

/-- The height of `[1 : b]` for `b` in a finite-dimensional intermediate field `F`: Mathlib's
relative height `logHeight₁ b` in `F` divided by `[F : ℚ]`. -/
theorem logHeight_one_eq (F : IntermediateField ℚ Qbar) [FiniteDimensional ℚ F] (b : F) :
    logHeight ![1, (b : Qbar)] = Height.logHeight₁ b / finrank ℚ F := by
  have h := logHeight_eq_of_mem F ![1, b]
  have hfun : (fun i => ((![1, b] : Fin 2 → F) i : Qbar)) = ![1, (b : Qbar)] := by
    ext i
    fin_cases i <;> rfl
  rw [hfun] at h
  rw [h, Height.logHeight_swap, ← Height.logHeight₁_eq_logHeight]

/-- **The height of an algebraic number** `a`: `h(a) = h_{ℚ(a)}(a) / [ℚ(a) : ℚ]`, the
normalization used for `Iut.Tripod.htCan` in the `iut` project. -/
theorem logHeight_one_eq_gen (a : Qbar) :
    logHeight ![1, a] = Height.logHeight₁ (AdjoinSimple.gen ℚ a) / finrank ℚ ℚ⟮a⟯ :=
  logHeight_one_eq ℚ⟮a⟯ (AdjoinSimple.gen ℚ a)

theorem logHeight_one_nonneg (a : Qbar) : 0 ≤ logHeight ![1, a] := logHeight_nonneg _

@[simp]
theorem logHeight_one_zero : logHeight ![1, (0 : Qbar)] = 0 := by
  have := logHeight_one_eq ⊥ 0
  rw [ZeroMemClass.coe_zero] at this
  rw [this, Height.logHeight₁_zero, zero_div]

/-- `h(a⁻¹) = h(a)`. -/
theorem logHeight_one_inv (a : Qbar) : logHeight ![1, a⁻¹] = logHeight ![1, a] := by
  have h1 := logHeight_one_eq ℚ⟮a⟯ (AdjoinSimple.gen ℚ a)⁻¹
  rw [IntermediateField.coe_inv, AdjoinSimple.coe_gen, Height.logHeight₁_inv] at h1
  rw [h1, logHeight_one_eq_gen]

/-- `h(-a) = h(a)`. -/
theorem logHeight_one_neg (a : Qbar) : logHeight ![1, -a] = logHeight ![1, a] := by
  have h1 := logHeight_one_eq ℚ⟮a⟯ (-AdjoinSimple.gen ℚ a)
  rw [IntermediateField.coe_neg, AdjoinSimple.coe_gen, Height.logHeight₁_neg] at h1
  rw [h1, logHeight_one_eq_gen]

section Pair

variable (a c : Qbar)

private lemma mem_adjoin_pair_left : a ∈ IntermediateField.adjoin ℚ ({a, c} : Set Qbar) :=
  IntermediateField.subset_adjoin _ _ (Set.mem_insert _ _)

private lemma mem_adjoin_pair_right : c ∈ IntermediateField.adjoin ℚ ({a, c} : Set Qbar) :=
  IntermediateField.subset_adjoin _ _ (Set.mem_insert_of_mem _ rfl)

/-- `h(a + c) ≤ h(a) + h(c) + log 2`. -/
theorem logHeight_one_add_le :
    logHeight ![1, a + c] ≤ logHeight ![1, a] + logHeight ![1, c] + Real.log 2 := by
  set F := IntermediateField.adjoin ℚ ({a, c} : Set Qbar)
  set ba : F := ⟨a, mem_adjoin_pair_left a c⟩
  set bc : F := ⟨c, mem_adjoin_pair_right a c⟩
  have hsum : logHeight ![1, a + c] = Height.logHeight₁ (ba + bc) / finrank ℚ F :=
    logHeight_one_eq F (ba + bc)
  have ha : logHeight ![1, a] = Height.logHeight₁ ba / finrank ℚ F := logHeight_one_eq F ba
  have hc : logHeight ![1, c] = Height.logHeight₁ bc / finrank ℚ F := logHeight_one_eq F bc
  rw [hsum, ha, hc]
  have hle := Height.logHeight₁_add_le ba bc
  rw [totalWeight_eq_finrank] at hle
  have hd := finrank_pos_real F
  rw [← add_div, div_le_iff₀ hd, add_mul, div_mul_cancel₀ _ hd.ne']
  linarith

/-- `h(a * c) ≤ h(a) + h(c)`. -/
theorem logHeight_one_mul_le :
    logHeight ![1, a * c] ≤ logHeight ![1, a] + logHeight ![1, c] := by
  set F := IntermediateField.adjoin ℚ ({a, c} : Set Qbar)
  set ba : F := ⟨a, mem_adjoin_pair_left a c⟩
  set bc : F := ⟨c, mem_adjoin_pair_right a c⟩
  have hmul : logHeight ![1, a * c] = Height.logHeight₁ (ba * bc) / finrank ℚ F :=
    logHeight_one_eq F (ba * bc)
  have ha : logHeight ![1, a] = Height.logHeight₁ ba / finrank ℚ F := logHeight_one_eq F ba
  have hc : logHeight ![1, c] = Height.logHeight₁ bc / finrank ℚ F := logHeight_one_eq F bc
  rw [hmul, ha, hc, ← add_div]
  exact div_le_div_of_nonneg_right (Height.logHeight₁_mul_le ba bc) (Nat.cast_nonneg _)

/-- **Translation estimate**: `|h(a + c) - h(a)| ≤ h(c) + log 2`. -/
theorem abs_logHeight_one_add_sub_le :
    |logHeight ![1, a + c] - logHeight ![1, a]| ≤ logHeight ![1, c] + Real.log 2 := by
  have h1 := logHeight_one_add_le a c
  have h2 := logHeight_one_add_le (a + c) (-c)
  rw [add_neg_cancel_right, logHeight_one_neg] at h2
  rw [abs_le]
  constructor <;> linarith

end Pair

/-! ### The local formula -/

/-- **The local formula for the absolute height**: for `y` a nonzero tuple in a
finite-dimensional intermediate field `F`,
`[F : ℚ] · h(y) = ∑_{w | ∞} mult w · log max_i |y_i|_w + ∑_{v ∤ ∞} log max_i |y_i|_v`. -/
theorem finrank_mul_logHeight_eq_sum (F : IntermediateField ℚ Qbar) [FiniteDimensional ℚ F]
    {y : ι → F} (hy : y ≠ 0) :
    finrank ℚ F * logHeight (fun i => (y i : Qbar)) =
      ∑ w : InfinitePlace F, (w.mult : ℝ) * Real.log (⨆ i, w (y i)) +
        ∑ᶠ v : FinitePlace F, Real.log (⨆ i, v (y i)) := by
  rw [logHeight_eq_of_mem F y, mul_div_cancel₀ _ (finrank_pos_real F).ne', logHeight_eq_sum hy]

/-- The local formula for an arbitrary number field `L` with an embedding `φ : L →+* ℚ̄`. -/
theorem finrank_mul_logHeight_comp_ringHom_eq_sum {L : Type*} [Field L] [NumberField L]
    (φ : L →+* Qbar) {y : ι → L} (hy : y ≠ 0) :
    finrank ℚ L * logHeight (fun i => φ (y i)) =
      ∑ w : InfinitePlace L, (w.mult : ℝ) * Real.log (⨆ i, w (y i)) +
        ∑ᶠ v : FinitePlace L, Real.log (⨆ i, v (y i)) := by
  rw [logHeight_comp_ringHom φ y,
    mul_div_cancel₀ _ (Nat.cast_pos.mpr (finrank_pos (R := ℚ) (M := L))).ne', logHeight_eq_sum hy]

/-- The local formula for the height of an element `b` of a number field `L` embedded in `ℚ̄`:
`[L : ℚ] · h(φ b) = ∑_{w | ∞} mult w · log⁺ |b|_w + ∑_{v ∤ ∞} log⁺ |b|_v`. -/
theorem finrank_mul_logHeight_one_comp_ringHom_eq_sum {L : Type*} [Field L] [NumberField L]
    (φ : L →+* Qbar) (b : L) :
    finrank ℚ L * logHeight ![1, φ b] =
      ∑ w : InfinitePlace L, (w.mult : ℝ) * Real.posLog (w b) +
        ∑ᶠ v : FinitePlace L, Real.posLog (v b) := by
  have H := logHeight_comp_ringHom φ ![1, b]
  have hfun : (fun i => φ ((![1, b] : Fin 2 → L) i)) = ![1, φ b] := by
    ext i
    fin_cases i <;> simp
  rw [hfun, Height.logHeight_swap, ← Height.logHeight₁_eq_logHeight] at H
  rw [H, mul_div_cancel₀ _ (Nat.cast_pos.mpr (finrank_pos (R := ℚ) (M := L))).ne',
    NumberField.logHeight₁_eq]

end Heights.Absolute
