import Mathlib

set_option linter.style.header false

/-!
# Relative heights under finite extensions of number fields

Mathlib's `Height.mulHeight` and `Height.logHeight` on a number field `K` are *relative*
heights: the product (resp. sum) over all places of `K`, with the archimedean places weighted by
`InfinitePlace.mult`.  This file proves the basic compatibility with finite extensions: for an
extension of number fields `K / k` and a tuple `y` of elements of `k`,
`mulHeight (algebraMap k K ∘ y) = mulHeight y ^ [K : k]`.

* At the archimedean places we pass to complex embeddings: a place `w` of `K` accounts for
  exactly `w.mult` embeddings `K →+* ℂ`, and every embedding `k →+* ℂ` has exactly `[K : k]`
  extensions to `K`.
* At the finite places we reduce to integral tuples by scaling (the height is scale invariant)
  and use Mathlib's identification of the finite part of the height with the inverse of the
  absolute norm of the ideal generated by the coordinates; the absolute norm of an extended ideal
  is the `[K : k]`-th power of the original one (`Ideal.absNorm_algebraMap`).

We also record invariance of the height under isomorphisms of number fields and the local
(logarithmic) formula for the height of a nonzero tuple.

A proof of the finite-place part via local degrees `e(w/v) f(w/v)` was given in the `iut`
project (by the iut contributors, `Iut.finHeight_algebraMap`); the argument here instead goes
through ideal norms, which Mathlib already provides.
-/

namespace Heights.Absolute

open NumberField Height Module
open scoped Finset

section Parts

variable {K : Type*} [Field K] [NumberField K] {ι : Type*}

/-- The archimedean part `∏_w (max_i |x_i|_w) ^ mult w` of the multiplicative height. -/
noncomputable def infPart (x : ι → K) : ℝ :=
  ∏ w : InfinitePlace K, (⨆ i, w (x i)) ^ w.mult

/-- The nonarchimedean part `∏_v max_i |x_i|_v` of the multiplicative height. -/
noncomputable def finPart (x : ι → K) : ℝ :=
  ∏ᶠ v : FinitePlace K, ⨆ i, v (x i)

lemma mulHeight_eq_infPart_mul_finPart {x : ι → K} (hx : x ≠ 0) :
    mulHeight x = infPart x * finPart x :=
  NumberField.mulHeight_eq hx

end Parts

/-! ### The archimedean places -/

section Infinite

open InfinitePlace

variable {K : Type*} [Field K] [NumberField K]

/-- A product over infinite places weighted by multiplicity is a product over complex
embeddings. -/
lemma prod_pow_mult_eq_prod_embeddings {M : Type*} [CommMonoid M] (g : InfinitePlace K → M) :
    ∏ w : InfinitePlace K, g w ^ w.mult = ∏ φ : K →+* ℂ, g (mk φ) := by
  classical
  rw [← Finset.prod_fiberwise Finset.univ mk (fun φ => g (mk φ))]
  refine Finset.prod_congr rfl fun w _ => ?_
  have : ∀ φ ∈ ({φ | mk φ = w} : Finset (K →+* ℂ)), g (mk φ) = g w := fun φ hφ => by
    rw [(Finset.mem_filter.mp hφ).2]
  rw [Finset.prod_congr rfl this, Finset.prod_const, card_filter_mk_eq]

variable {k : Type*} [Field k] [NumberField k] [Algebra k K]

open scoped Classical in
/-- Every complex embedding of `k` has exactly `[K : k]` extensions to `K`. -/
lemma card_filter_comp_algebraMap_eq (φ : k →+* ℂ) :
    #{ψ : K →+* ℂ | ψ.comp (algebraMap k K) = φ} = finrank k K := by
  classical
  letI : Algebra k ℂ := φ.toAlgebra
  rw [← AlgHom.card k K ℂ, ← Finset.card_univ]
  symm
  refine Finset.card_nbij (fun σ => (σ : K →+* ℂ)) (fun σ _ => ?_)
    (fun σ _ τ _ h => AlgHom.coe_ringHom_injective h) (fun ψ hψ => ?_)
  · simp only [Finset.coe_filter, Finset.mem_univ, true_and, Set.mem_setOf_eq]
    ext x
    simp [RingHom.algebraMap_toAlgebra]
  · simp only [Finset.coe_filter, Finset.mem_univ, true_and, Set.mem_setOf_eq] at hψ
    refine ⟨⟨ψ, fun x => ?_⟩, by simp, rfl⟩
    simp [RingHom.algebraMap_toAlgebra, ← hψ]

/-- Summing over the complex embeddings of `K` a function of the restriction to `k`. -/
lemma prod_comp_algebraMap {M : Type*} [CommMonoid M] (g : (k →+* ℂ) → M) :
    ∏ ψ : K →+* ℂ, g (ψ.comp (algebraMap k K)) = (∏ φ : k →+* ℂ, g φ) ^ finrank k K := by
  classical
  rw [← Finset.prod_fiberwise Finset.univ (fun ψ : K →+* ℂ => ψ.comp (algebraMap k K)),
    ← Finset.prod_pow]
  refine Finset.prod_congr rfl fun φ _ => ?_
  have : ∀ ψ ∈ ({ψ | ψ.comp (algebraMap k K) = φ} : Finset (K →+* ℂ)),
      g (ψ.comp (algebraMap k K)) = g φ := fun ψ hψ => by rw [(Finset.mem_filter.mp hψ).2]
  rw [Finset.prod_congr rfl this, Finset.prod_const, card_filter_comp_algebraMap_eq]

lemma infPart_algebraMap {ι : Type*} (y : ι → k) :
    infPart (fun i => algebraMap k K (y i)) = infPart y ^ finrank k K := by
  simp only [infPart]
  rw [prod_pow_mult_eq_prod_embeddings (fun w : InfinitePlace K => ⨆ i, w (algebraMap k K (y i))),
    prod_pow_mult_eq_prod_embeddings (fun w : InfinitePlace k => ⨆ i, w (y i)),
    ← prod_comp_algebraMap (fun φ : k →+* ℂ => ⨆ i, (mk φ) (y i))]
  refine Finset.prod_congr rfl fun ψ _ => ?_
  rw [← comap_mk]
  rfl

end Infinite

/-! ### The finite places -/

section Finite

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]

attribute [local instance] FractionRing.liftAlgebra in
/-- The absolute norm of an extended ideal is the `[K : k]`-th power of the absolute norm. -/
lemma absNorm_map_algebraMap (I : Ideal (𝓞 k)) :
    Ideal.absNorm (I.map (algebraMap (𝓞 k) (𝓞 K))) = Ideal.absNorm I ^ finrank k K := by
  rw [Ideal.absNorm_algebraMap, Algebra.finrank_eq_of_equiv_equiv
      (FractionRing.algEquiv (𝓞 k) k).toRingEquiv (FractionRing.algEquiv (𝓞 K) K).toRingEquiv]
  ext
  exact IsFractionRing.algEquiv_commutes (FractionRing.algEquiv (𝓞 k) k)
    (FractionRing.algEquiv (𝓞 K) K) _

lemma finPart_algebraMap_of_integral {ι : Type*} [Finite ι] (z : ι → 𝓞 k) (hz : z ≠ 0) :
    finPart (fun i => algebraMap k K (z i)) = finPart (fun i => (z i : k)) ^ finrank k K := by
  have hz' : (fun i => algebraMap (𝓞 k) (𝓞 K) (z i)) ≠ 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hz
    refine Function.ne_iff.mpr ⟨i, ?_⟩
    simpa using hi
  have h1 := absNorm_mul_finprod_finitePlace_eq_one (K := k) hz
  have h2 := absNorm_mul_finprod_finitePlace_eq_one (K := K) hz'
  have hspan : Ideal.span (Set.range fun i => algebraMap (𝓞 k) (𝓞 K) (z i)) =
      (Ideal.span (Set.range z)).map (algebraMap (𝓞 k) (𝓞 K)) := by
    rw [Ideal.map_span, ← Set.range_comp]
    rfl
  rw [hspan, absNorm_map_algebraMap] at h2
  have hN : (Ideal.absNorm (Ideal.span (Set.range z)) : ℝ) ≠ 0 := by
    intro h
    rw [h, zero_mul] at h1
    exact zero_ne_one h1
  have e1 : finPart (fun i => (z i : k)) = (Ideal.absNorm (Ideal.span (Set.range z)) : ℝ)⁻¹ :=
    eq_inv_of_mul_eq_one_right h1
  have e2 : finPart (fun i => algebraMap k K (z i)) =
      ((Ideal.absNorm (Ideal.span (Set.range z)) : ℝ) ^ finrank k K)⁻¹ := by
    refine eq_inv_of_mul_eq_one_right ?_
    rw [← h2]
    push_cast
    rfl
  rw [e1, e2, inv_pow]

end Finite

/-! ### Extension invariance -/

section Extension

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]
variable {ι : Type*} [Finite ι]

/-- Every tuple of elements of a number field has a nonzero integer multiple with integral
coordinates. -/
lemma exists_int_smul_integral (y : ι → k) :
    ∃ d : ℤ, d ≠ 0 ∧ ∃ z : ι → 𝓞 k, ∀ i, (z i : k) = (d : k) * y i := by
  classical
  have := Fintype.ofFinite ι
  obtain ⟨d, hd, hint⟩ := exists_integral_multiples ℤ ℚ (L := k) (Finset.univ.image y)
  refine ⟨d, hd, fun i => ⟨d • y i, ?_⟩, fun i => ?_⟩
  · exact (hint _ (Finset.mem_image_of_mem _ (Finset.mem_univ i)))
  · simp [zsmul_eq_mul]

/-- **Extension formula for the relative multiplicative height**:
`H_K(y) = H_k(y) ^ [K : k]` for a tuple `y` of elements of `k`. -/
theorem mulHeight_algebraMap (y : ι → k) :
    mulHeight (fun i => algebraMap k K (y i)) = mulHeight y ^ finrank k K := by
  rcases eq_or_ne y 0 with rfl | hy
  · simp
  obtain ⟨d, hd, z, hz⟩ := exists_int_smul_integral y
  have hdk : (d : k) ≠ 0 := Int.cast_ne_zero.mpr hd
  have hdK : (d : K) ≠ 0 := Int.cast_ne_zero.mpr hd
  have e1 : mulHeight y = mulHeight (fun i => (z i : k)) := by
    rw [← mulHeight_smul_eq_mulHeight y hdk]
    congr 1
    ext i
    simp [hz]
  have e2 : mulHeight (fun i => algebraMap k K (y i)) =
      mulHeight (fun i => algebraMap k K (z i)) := by
    rw [← mulHeight_smul_eq_mulHeight _ hdK]
    congr 1
    ext i
    simp [hz]
  have hz0 : z ≠ 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hy
    refine Function.ne_iff.mpr ⟨i, fun h => ?_⟩
    have := hz i
    rw [h] at this
    simp only [Pi.zero_apply, map_zero] at this
    exact (mul_ne_zero hdk hi) this.symm
  have hzk : (fun i => (z i : k)) ≠ 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hz0
    exact Function.ne_iff.mpr ⟨i, by simpa using hi⟩
  have hzK : (fun i => algebraMap k K (z i)) ≠ 0 := by
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hz0
    exact Function.ne_iff.mpr ⟨i, by simpa using hi⟩
  rw [e1, e2, mulHeight_eq_infPart_mul_finPart hzk, mulHeight_eq_infPart_mul_finPart hzK,
    infPart_algebraMap, finPart_algebraMap_of_integral z hz0, mul_pow]

/-- **Extension formula for the relative logarithmic height**:
`h_K(y) = [K : k] · h_k(y)` for a tuple `y` of elements of `k`. -/
theorem logHeight_algebraMap (y : ι → k) :
    logHeight (fun i => algebraMap k K (y i)) = finrank k K * logHeight y := by
  rw [logHeight_eq_log_mulHeight, mulHeight_algebraMap, Real.log_pow, logHeight_eq_log_mulHeight]

omit [Algebra k K] in
/-- The normalized height `h_K(y) / [K : ℚ]` is unchanged by any embedding of number fields. -/
theorem logHeight_comp_ringHom_div_finrank (f : k →+* K) (y : ι → k) :
    logHeight (fun i => f (y i)) / finrank ℚ K = logHeight y / finrank ℚ k := by
  letI := f.toAlgebra
  have h := logHeight_algebraMap (K := K) y
  rw [RingHom.algebraMap_toAlgebra] at h
  rw [h, ← Module.finrank_mul_finrank ℚ k K]
  have hk : (finrank ℚ k : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  have hkK : (finrank k K : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  push_cast
  field_simp

omit [Algebra k K] in
/-- The relative height is invariant under isomorphisms of number fields. -/
theorem logHeight_comp_ringEquiv (e : k ≃+* K) (y : ι → k) :
    logHeight (fun i => e (y i)) = logHeight y := by
  have h := logHeight_comp_ringHom_div_finrank e.toRingHom y
  have hfin : finrank ℚ k = finrank ℚ K :=
    (AlgEquiv.ofRingEquiv (f := e) fun q => map_ratCast e q).toLinearEquiv.finrank_eq
  have hk : (finrank ℚ k : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr finrank_pos.ne'
  rw [← hfin] at h
  exact (div_left_inj' hk).mp h

end Extension

/-! ### The local formula -/

section Local

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} [Finite ι]

omit [NumberField K] in
lemma iSup_infinitePlace_pos {x : ι → K} (hx : x ≠ 0) (w : InfinitePlace K) :
    0 < ⨆ i, w (x i) := by
  obtain ⟨i, hi⟩ := Function.ne_iff.mp hx
  exact lt_of_lt_of_le (InfinitePlace.pos_iff.mpr hi) (Finite.le_ciSup_of_le i le_rfl)

lemma iSup_finitePlace_pos {x : ι → K} (hx : x ≠ 0) (v : FinitePlace K) :
    0 < ⨆ i, v (x i) := by
  obtain ⟨i, hi⟩ := Function.ne_iff.mp hx
  exact lt_of_lt_of_le (FinitePlace.pos_iff.mpr hi) (Finite.le_ciSup_of_le i le_rfl)

/-- **The local formula for the relative logarithmic height** of a nonzero tuple:
`h_K(x) = ∑_{w | ∞} mult w · log max_i |x_i|_w + ∑_{v ∤ ∞} log max_i |x_i|_v`. -/
theorem logHeight_eq_sum {x : ι → K} (hx : x ≠ 0) :
    logHeight x = ∑ w : InfinitePlace K, (w.mult : ℝ) * Real.log (⨆ i, w (x i)) +
      ∑ᶠ v : FinitePlace K, Real.log (⨆ i, v (x i)) := by
  rw [logHeight_eq_log_mulHeight, NumberField.mulHeight_eq hx,
    Real.log_mul (Finset.prod_ne_zero_iff.mpr fun w _ =>
      (pow_pos (iSup_infinitePlace_pos hx w) _).ne')
      (finprod_ne_zero fun v => (iSup_finitePlace_pos hx v).ne'),
    Real.log_prod fun w _ => (pow_pos (iSup_infinitePlace_pos hx w) _).ne',
    Real.log_finprod fun v => iSup_finitePlace_pos hx v]
  simp only [Real.log_pow]

end Local

end Heights.Absolute
